### PR TITLE
Reproduce tool fixes.

### PR DESCRIPTION
**Pull request by mbarbella-chromium**
PTAL. If the installed version of distutils is the Python 3.8 version, this seems to cause issues if we attempt to run under Python 3.7. Switching the order of this check appears to work fine.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
i think this will break deployment since we still need to deploy as 3.7, need to discuss a plan with oliver.

**Comment by mbarbella-chromium** [comment]
Ah, good catch. I'll update this to favor 3.8 in the reproduce tool case only.

**Comment by mbarbella-chromium** [comment]
Though if it's not much work to support 3.8 in deployment, maybe it's worth considering. I'll hold off until we hear from Oliver.

**Comment by oliverchang** [comment]
Supporting 3.8 deployment will be a bit of work and needs more thought. It's difficult to upgrade some of our bots (internal chromium ones etc) so the proper fix here would be to fix our deployment so that we build multiple packages for 3.7, 3.8 (and 3.9 and whatever comes after...) as these aren't backwards compatible.  Let's just go with the quick fix for reproduce tool first.

**Comment by mbarbella-chromium** [comment]
SGTM.

**Comment by mbarbella-chromium** [comment]
Made a few changes here and added another batch of fixes. PTAL.

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
