### PR TITLE
Added 'None' check for testcase_id in issue_redirector.py

### PR DESCRIPTION
**Pull request by Onkar1300**
Redirect the page to 'Testcase not found' instead of reporting error log when accessing issue with 'None' testcase_id

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Not sure this is a worthwhile change. Why do you want it?

**Comment by Onkar1300** [comment]
> Not sure this is a worthwhile change. Why do you want it?

Hi Jonathan,
If https://clusterfuzz.corp.google.com/issue is accesed without any testcase_id, the argument to '[get_testcase()](https://github.com/google/clusterfuzz/blob/8c2f3bcebd061dfdd40470ee2e2ddab6bf6637e1/src/appengine/handlers/issue_redirector.py#L27)' is None which eventually leads to the following error: 
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
To resolve the issue, a None check is added to redirect to None 'testcase_id' doesn't exist. instead of reporting TypeError.

**Comment by jonathanmetzman** [comment]
> > Not sure this is a worthwhile change. Why do you want it?
> 
> Hi Jonathan, If https://clusterfuzz.corp.google.com/issue is accesed without any testcase_id, the argument to '[get_testcase()](https://github.com/google/clusterfuzz/blob/8c2f3bcebd061dfdd40470ee2e2ddab6bf6637e1/src/appengine/handlers/issue_redirector.py#L27)' is None which eventually leads to the following error: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' To resolve the issue, a None check is added to redirect to None 'testcase_id' doesn't exist. instead of reporting TypeError.

When are you directed to this URL though?

**Comment by Onkar1300** [comment]
> > > Not sure this is a worthwhile change. Why do you want it?
> > 
> > 
> > Hi Jonathan, If https://clusterfuzz.corp.google.com/issue is accesed without any testcase_id, the argument to '[get_testcase()](https://github.com/google/clusterfuzz/blob/8c2f3bcebd061dfdd40470ee2e2ddab6bf6637e1/src/appengine/handlers/issue_redirector.py#L27)' is None which eventually leads to the following error: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' To resolve the issue, a None check is added to redirect to None 'testcase_id' doesn't exist. instead of reporting TypeError.
> 
> When are you directed to this URL though?

Whenever web-security-scanner@google.com tries to access https://clusterfuzz.corp.google.com/issue, it triggers this error log in ClusterFuzz logs

**Comment by jonathanmetzman** [comment]
Why is this bot trying to access that URL? Can the bot be fixed?

**Comment by Onkar1300** [comment]
> Why is this bot trying to access that URL? Can the bot be fixed?

it seems like for security checks, [web-security-scanner@google.com](mailto:web-security-scanner@google.com) tries to access https://clusterfuzz.corp.google.com/issue which raises the above error. We are not aware how to fix the bot such that it does not access https://clusterfuzz.corp.google.com/issue.

**Comment by jonathanmetzman** [comment]
OK, then I don't think we should make this change. We shouldn't special case things so a security scanner doesn't get a 500.

**Pull request closed without merging**
