### PR TITLE
Force all chromium labels to go through the substitution mapping and add more logging

### PR DESCRIPTION
**Pull request by rmistry**

### CODE REVIEW

**Comment by rmistry** [comment]
PTAL @jonathanmetzman 
CC @micahbales

**Comment by rmistry** [comment]
Oh wait, there is a test failure

**Comment by rmistry** [comment]
I don't think this will work. It would also lose the labels.added and labels.removed part.

Maybe I should only look at labels.added..

**Comment by rmistry** [comment]
OK PTAL

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
