### PR TITLE
Install google cloud batch

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Review by oliverchang — COMMENTED** [review]
Nice! can you bump https://github.com/google/clusterfuzz/blob/master/src/platform_requirements.txt as well?

**Comment by jonathanmetzman** [comment]
> Nice! can you bump https://github.com/google/clusterfuzz/blob/master/src/platform_requirements.txt as well?

Done. How do I verify my fix didn't break anything.

**Comment by oliverchang** [comment]
> > Nice! can you bump https://github.com/google/clusterfuzz/blob/master/src/platform_requirements.txt as well?
> 
> Done. How do I verify my fix didn't break anything.

If tests work locally this should be fine. This is to vendor dependencies that have platform specific bits when we deploy, so a little hard to test this more comprehensively atm.

**Comment by jonathanmetzman** [comment]
Deploy failing with this error:
```
Exception: Failed to find package in supported platforms: %s('manylinux2010_x86_64', 'manylinux1_x86_64')
    str(pip_platforms))
  File "src/local/butler/common.py", line 314, in _install_platform_pip
    platform_name=platform_name)
  File "src/local/butler/common.py", line 335, in install_dependencies
    common.install_dependencies(platform_name=platform_name)
  File "src/local/butler/package.py", line 85, in package
    revision, platform_name=platform_name, python3=is_python3))
  File "src/local/butler/deploy.py", line 489, in execute
    return command.execute(args)
  File "butler.py", line 259, in main
    sys.exit(main())
  File "butler.py", line 273, in <module>
Traceback (most recent call last):
Did not find package for platform: manylinux1_x86_64
| Return code is non-zero (1).
| ERROR: No matching distribution found for grpcio==1.54.2
| ERROR: Could not find a version that satisfies the requirement grpcio==1.54.2 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.0rc3, 1.13.0, 1.14.0rc1, 1.14.0rc2, 1.14.0, 1.14.1, 1.14.2rc1, 1.14.2, 1.15.0rc1, 1.15.0, 1.16.0rc1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.18.0, 1.19.0, 1.20.0rc1, 1.20.0rc2, 1.20.0rc3, 1.20.0, 1.20.1, 1.21.0rc1, 1.21.1rc1, 1.21.1, 1.22.0rc1, 1.22.0, 1.22.1, 1.23.0rc1, 1.23.0, 1.23.1, 1.24.0rc1, 1.24.0, 1.24.1, 1.24.3, 1.25.0rc1, 1.25.0, 1.26.0rc1, 1.26.0, 1.27.0rc1, 1.27.1, 1.27.2)
Running: pip3 download --no-deps --only-binary=:all: --platform=manylinux1_x86_64 --abi=cp37m -r src/platform_requirements.txt -d /tmp/tmpitm5tyux
Did not find package for platform: manylinux2010_x86_64
| Return code is non-zero (1).
| ERROR: No matching distribution found for grpcio==1.54.2
| ERROR: Could not find a version that satisfies the requirement grpcio==1.54.2 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.0rc3, 1.13.0, 1.14.0rc1, 1.14.0rc2, 1.14.0, 1.14.1, 1.14.2rc1, 1.14.2, 1.15.0rc1, 1.15.0, 1.16.0rc1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.18.0, 1.19.0, 1.20.0rc1, 1.20.0rc2, 1.20.0rc3, 1.20.0, 1.20.1, 1.21.0rc1, 1.21.1rc1, 1.21.1, 1.22.0rc1, 1.22.0, 1.22.1, 1.23.0rc1, 1.23.0, 1.23.1, 1.24.0rc1, 1.24.0, 1.24.1, 1.24.3, 1.25.0rc1, 1.25.0, 1.26.0rc1, 1.26.0, 1.27.0rc1, 1.27.0rc2, 1.27.1, 1.27.2, 1.28.0rc1, 1.28.0rc2, 1.28.1, 1.29.0, 1.30.0, 1.31.0, 1.32.0, 1.33.1, 1.33.2, 1.34.0rc1, 1.34.0, 1.34.1, 1.35.0rc1, 1.35.0, 1.36.0rc1, 1.36.0, 1.36.1, 1.37.0rc1, 1.37.0, 1.37.1, 1.38.0rc1, 1.38.0, 1.38.1, 1.39.0rc1, 1.39.0, 1.40.0rc1, 1.40.0, 1.41.0rc2, 1.41.0, 1.41.1, 1.42.0rc1, 1.42.0, 1.43.0rc1, 1.43.0, 1.44.0rc1, 1.44.0rc2, 1.44.0, 1.45.0rc1, 1.45.0, 1.46.0rc1, 1.46.0rc2, 1.46.0, 1.46.1, 1.46.3, 1.46.5)
Running: pip3 download --no-deps --only-binary=:all: --platform=manylinux2010_x86_64 --abi=cp37m -r src/platform_requirements.txt -d /tmp/tmp9hb7p767
| Successfully installed antlr4-python3-runtime-4.7.2 attrs-23.1.0 automat-22.10.0 cachetools-4.2.4 certifi-2023.5.7 chardet-3.0.4 constantly-15.1.0 distro-1.8.0 ecdsa-0.18.0 google-api-core-1.34.0 google-api-python-client-1.8.3 google-auth-1.25.0 google-auth-httplib2-0.1.0 google-auth-oauthlib-0.4.1 google-cloud-batch-0.2.0 google-cloud-core-1.4.1 google-cloud-datastore-1.12.0 google-cloud-logging-1.15.0 google-cloud-monitoring-0.36.0 google-cloud-ndb-1.4.0 google-cloud-profiler-1.0.3 google-cloud-storage-1.28.1 google-resumable-media-0.5.1 googleapis-common-protos-1.59.0 grpc-google-iam-v1-0.12.6 grpcio-1.54.2 grpcio-status-1.48.2 httplib2-0.19.0 hyperlink-21.0.0 idna-2.8 importlib-metadata-6.6.0 incremental-22.10.0 lxml-4.6.5 mozfile-3.0.0 mozinfo-1.2.2 mozprocess-1.1.0 oauth2client-4.1.3 oauthlib-3.2.2 proto-plus-1.22.2 protobuf-3.20.3 pyasn1-0.5.0 pyasn1-modules-0.3.0 pyhamcrest-2.0.4 pyparsing-2.4.7 pytz-2023.3 pyyaml-5.4 redis-3.3.11 requests-2.21.0 requests-oauthlib-1.3.1 rsa-4.9 setuptools-67.8.0 six-1.14.0 tlslite-ng-0.7.6 twisted-20.3.0 typing-extensions-4.6.3 uritemplate-3.0.1 urllib3-1.24.3 zipp-3.15.0 zope.interface-6.0
| twine 4.0.2 requires urllib3>=1.26.0, but you have urllib3 1.24.3 which is incompatible.
```

**Pull request merged**
