### PR TITLE
Try different strategy for fixing source updating

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Try to make files writeable on unpack.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
This doesn't work, because on startup the zipfile is unpacked by different means. We need to ensure the zip doesn't contain any readonly files.

**Comment by oliverchang** [comment]
> This doesn't work, because on startup the zipfile is unpacked by different means. We need to ensure the zip doesn't contain any readonly files.

Hmm, sounds like a step we just need to do on the source deployment then?

**Comment by jonathanmetzman** [comment]
Ha yep, PR up now.

**Comment by jonathanmetzman** [comment]
Funny how we thought of each possible option in the same order.

**Pull request merged**
