### PR TITLE
Use the "Component Tags" custom field to store additional components in google_issue_tracker

### PR DESCRIPTION
**Pull request by rmistry**
Google Issue Tracker has support for only one component per issue. The Chrome-on-Buganizer team has added a "Component Tags" custom field with which each issue can have multiple components (similar to behavior in Monorail).

This required refactoring of how components are handled in google_issue_tracker.

More context is in b/315853316

### CODE REVIEW

**Comment by rmistry** [comment]
PTAL @jonathanmetzman @oliverchang 
CC @micahbales

**Comment by jonathanmetzman** [comment]
Something is wrong with our testing.

**Pull request merged**
