### PR TITLE
remove duplicated env var constant for AFL_EXPAND_HAVOC_NOW

### PR DESCRIPTION
**Pull request by yuawn**

### CODE REVIEW

**Comment by oliverchang** [comment]
@jonathanmetzman could you please help review this?

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by yuawn** [comment]
Hi @jonathanmetzman
I fixed the pylint issue.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
