### PR TITLE
Fix pipenv issue in reproduce tool

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Reproduce tool used pipenv in a different way than install_deps_linux.bash
which uses it correctly. Change manner to the correct one.

This fixes the issue I experienced in #2175 but maybe not the other issue reported to me.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I don't know how to deploy this fix. @inferno-chromium can you tell me how please?

**Review by inferno-chromium — APPROVED** [review]
To deploy

```
git push origin :refs/tags/reproduce-tool-stable
git tag -fa reproduce-tool-stable
git push origin tags/reproduce-tool-stable
```

**Comment by inferno-chromium** [comment]
Does this resolve https://bugs.chromium.org/p/chromium/issues/detail?id=1146516#c5 ?

**Comment by jonathanmetzman** [comment]
> Does this resolve https://bugs.chromium.org/p/chromium/issues/detail?id=1146516#c5 ?

I can see how it might. But I don't know as I couldn't reproduce that issue.

**Comment by inferno-chromium** [comment]
> > Does this resolve https://bugs.chromium.org/p/chromium/issues/detail?id=1146516#c5 ?
> 
> I can see how it might. But I don't know as I couldn't reproduce that issue.

Sure, lets give it a try.

**Review by oliverchang — COMMENTED** [review]
LGTM

**Pull request merged**
