### PR TITLE
Remove fork mode flag before merge step.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Basically noticed breakage when testing heartbleeed example locally. If fork mode strategy was picked, then merge step would hang since it would have -fork=1 and that will cause it to run fuzzing for that time duration :(

**Comment by inferno-chromium** [comment]
Question for you guys: should max_len be removed before merge step ? that would be the only big change after this and need test updates.

**Comment by Dor1s** [comment]
> Question for you guys: should max_len be removed before merge step ?

Yes, absolutely

**Pull request merged**
