### PR TITLE
Make SystemSan crashes reproducible.

### LINKED ISSUE #2868: systemsan: fix reproduction.

### PR DESCRIPTION
**Pull request by oliverchang**
Fixes #2868.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM.
Thanks for doing this.
Are these crashes going to be filed as a result of this?

**Comment by oliverchang** [comment]
Nope, we check these in https://github.com/google/clusterfuzz/blob/5d70a7a15b380a454f5efcd084b7cf42edc615a0/src/clusterfuzz/_internal/crash_analysis/crash_analyzer.py#L407 and mark them as experimental.

**Comment by jonathanmetzman** [comment]
I wonder if this is causing some issues: https://console.cloud.google.com/errors/CNCrqunpl4b6OA?project=google.com:clusterfuzz&time=P30D&utm_source=error-reporting-notification&utm_medium=email&utm_content=new-error&pli=1&rapt=AEjHL4N_Nan9Z3rAsNoTlEbb-YRVFyb5d3lV0RF97hXDXX7-8plkSoqOr5tYXO_c9xWvpLaObX2ss-Wuy-1LR-PzvcGaJ2e0pg

**Comment by oliverchang** [comment]
Yeah, thanks for pointing that out. Fixed in https://github.com/google/clusterfuzz/pull/2875

**Pull request merged**
