### PR TITLE
allow badly setup projects for afl++ still working

### PR DESCRIPTION
**Pull request by vanhauser-thc**
For project that dlopen() instrumented libraries this is an issue for afl++ collision free coverage as the map size must be known when the forkserver is run.
So the current implementation bails when this is detected as this means the fuzzing setup is inefficient.
The solution is to AFL_PRELOAD such dlopen'ed libs.
For the time being though lets allow such setup to still run (less efficient) instead of aborting.

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]
LGTM, thank! I'll let @jonathanmetzman take a look as well in case he has any concerns.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Will merge on monday

**Comment by oliverchang** [comment]
@jonathanmetzman is this ready to merge?

**Comment by vanhauser-thc** [comment]
it should be merged asap to ensure that all projects are able to run.

**Pull request merged**
