### PR TITLE
Revert "Move tests to proper location (#4185)"

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This reverts commit dc2f4acfe68b69e70f246e0adb1e687652ebc7c7.

It causes a lot of failures when testing locally in parallel.

### CODE REVIEW

**Comment by vitorguidi** [comment]
This is having some sort of interaction with past PRs, causing tests to fail:

#4295 
#4296 
#4289

**Comment by jonathanmetzman** [comment]
> This is having some sort of interaction with past PRs, causing tests to fail:
> 
> #4295 #4296 #4289

You mean the old PR right? Not the new one?

**Comment by jonathanmetzman** [comment]
> This is having some sort of interaction with past PRs, causing tests to fail:
> 
> #4295 #4296 #4289

Oh actually, you mean that the old tests are failing?

**Comment by vitorguidi** [comment]
> > This is having some sort of interaction with past PRs, causing tests to fail:
> > #4295 #4296 #4289
> 
> Oh actually, you mean that the old tests are failing?

When these PRs were merged, tests passed. With your PR, some tests that belong to their sections are failing.

**Comment by jonathanmetzman** [comment]
Is https://github.com/google/clusterfuzz/pull/4296 a mistake? This is just a log change.

**Review by vitorguidi — APPROVED** [review]
lgtm

**Pull request merged**
