### PR TITLE
Add 'killall' Package to base/Dockerfile

### PR DESCRIPTION
**Pull request by kalder**

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]
thanks!

**Comment by inferno-chromium** [comment]
why do you need this, cant you use https://github.com/google/clusterfuzz/blob/master/src/python/system/process_handler.py#L601 ?

**Comment by oliverchang** [comment]
> why do you need this, cant you use https://github.com/google/clusterfuzz/blob/master/src/python/system/process_handler.py#L601 ?

I believe this is called from an external shell script. Seems like something we should have in the base image (and we call it from other places too like https://github.com/google/clusterfuzz/blob/f9b0b8c684cdf57cdf999c34eff4aea07dffa8f6/src/python/system/process_handler.py#L330)

**Comment by inferno-chromium** [comment]
> > why do you need this, cant you use https://github.com/google/clusterfuzz/blob/master/src/python/system/process_handler.py#L601 ?
> 
> I believe this is called from an external shell script. Seems like something we should have in the base image (and we call it from other places too like
> 
> https://github.com/google/clusterfuzz/blob/f9b0b8c684cdf57cdf999c34eff4aea07dffa8f6/src/python/system/process_handler.py#L330
> 
> )

ah in chromium, we get it from its install script. makes sense to push in base image.

**Pull request merged**
