### PR TITLE
[minimize] Fix bug caused by serializing a testcase gotten during main.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Output doesn't support serializing objects, only wrapped ones.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @pgrace-google 
One error to fix.

**Comment by jonathanmetzman** [comment]
TBR

**Comment by pgrace-google** [comment]
oh dang
handle_minimize_setup_error that uses this output didnt need testcase anyway so, nice!

but whats the difference between that testcase and the testcase being passed in at the end of main in minimize, or places in analyze_task? I dont see it being explicitly differently treated

**Comment by jonathanmetzman** [comment]
>but whats the difference between that testcase and the testcase being passed in at the end of main in minimize, or places in analyze_task? I dont see it being explicitly differently treated

The difference is based on a too-clever solution I made where entities we deserialize from input are wrapped with another object that passes through any variable setting/accesses to the underlying db entity. This wrapper tracks the changes and so it makes it somewhat easier to update only the changed fields. But I think this may not be so useful in the end as I'd rather we send the fields we want in Output then rely on magic like this.

**Comment by oliverchang** [comment]
+1 to removing magic if we can.

**Pull request merged**
