### PR TITLE
For OSS-Fuzz, grant project access to mutator plugins bucket.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
TBR for fixing exception on OSS-Fuzz
```
Forbidden: 403 GET https://www.googleapis.com/storage/v1/b/clusterfuzz-external-mutator-plugins/o?prefix=&projection=noAcl: bot-llvm@clusterfuzz-external.iam.gserviceaccount.com does not have storage.objects.list access to clusterfuzz-external-mutator-plugins.
```

**Comment by jonathanmetzman** [comment]
LGTM

**Pull request merged**
