### PR TITLE
Updated Files From Other Repository.

### PR DESCRIPTION
**Pull request by RyanBCao**
- Again, all code here has been reviewed.
- Removed several dependencies (`tqdm`, `natsort`, `matplotlib`, and `seaborn`) not installed in clusterfuzz's Pipfile.
- Removed several [plotting/statistics] files relevant for experimentation but not deployment.

### CODE REVIEW

**Comment by RyanBCao** [comment]
Diff is fixed!

**Review by mbarbella-chromium — APPROVED** [review]

**Review by Dor1s — APPROVED** [review]

**Comment by mbarbella-chromium** [comment]
Looks like travis is failing due to an import order issue. Could you take a look? Once CI is green I'll merge this.

**Pull request merged**
