### PR TITLE
Update image in index.md

### PR DESCRIPTION
**Pull request by Shivam7-1**
Update image in index.md
Fix: https://github.com/google/clusterfuzz/issues/1881

### CODE REVIEW

**Comment by Shivam7-1** [comment]
https://github.com/google/clusterfuzz/issues/1881

**Comment by Shivam7-1** [comment]
[https://github.com/google/clusterfuzz/issues/1881](url)

**Comment by Shivam7-1** [comment]
Fixes:#https://github.com/google/clusterfuzz/issues/1881

**Comment by inferno-chromium** [comment]
The documentation is made using jekyll, it works - https://google.github.io/clusterfuzz/

**Pull request closed without merging**
