### PR TITLE
Add an ignore frame for unexpected-exit in MSan.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/list?colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary&q=%22Unexpected-exit%22&can=2

**Comment by inferno-chromium** [comment]
TBR

**Comment by mbarbella-chromium** [comment]
LGTM

**Pull request merged**
