### PR TITLE
Make Exception naming style-conformant, modernize

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@oliverchang Do we want something like this? I went down a rabbit hole after renaming some exceptions. Most of the transformations were automated so it's not a lot of wasted effort.

**Comment by jonathanmetzman** [comment]
I think the f-string transform is the most dubious value change. The others like getting rid of six and making exceptions end in "Error" instead of "Exception" seem more worthwhile, since they are solvable problems (we will probably never entirely get rid of .format)

**Comment by oliverchang** [comment]
definitely seems worthwhile as a general code cleanup to me! 

+1 to f-string change being a little dubious. It's also the most riskiest of all these changes, so we could just omit that for now.

**Comment by jonathanmetzman** [comment]
Done.

**Review by oliverchang — APPROVED** [review]
LGTM. Spot checked various places but obviously couldn't comprehensively review this whol PR :) Please monitor carefully.

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
