### PR TITLE
Don't enforce content security policies in local development mode (#260).

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Shouldn't the development mode model the production one? This might make more of a mess in the long run.

**Comment by inferno-chromium** [comment]
Development mode relies on emulators, so can't always model the production mode exactly. Emulators rely on different local ports (see https://github.com/google/clusterfuzz/blob/master/src/local/butler/constants.py#L65), so we gets different hostnames localhost:9000, localhost:9008 for gcs, etc which fails in CSP. I dont see value in enabling CSP locally since it never talks to external hosts, but only emulators on local ports.

**Comment by jonathanmetzman** [comment]
> Development mode relies on emulators, so can't always model the production mode exactly. Emulators rely on different local ports (see https://github.com/google/clusterfuzz/blob/master/src/local/butler/constants.py#L65), so we gets different hostnames localhost:9000, localhost:9008 for gcs, etc which fails in CSP. I dont see value in enabling CSP locally since it never talks to external hosts, but only emulators on local ports.

ACK

**Pull request merged**
