### PR TITLE
Remove calculation of impact on production builds.

### PR DESCRIPTION
**Pull request by adetaylor**
ClusterFuzz previously had two mechanisms to calculate impact on production builds:

* Plan A: attempt the test case on builds corresponding to stable, beta and dev channels.
* Plan B: if no such builds were available, estimate based on bisection ranges and branch points.

Plan A stopped working properly because we stopped getting a feed of production builds, for unknown reasons. Additionally, it was on shaky ground because those channels imprecisely matched the numeric release channels (sometimes there's a whole branch in between 'beta' and 'dev', for example).

With this PR we remove all the code related to Plan A and switch to Plan B.

Bug: https://crbug.com/1383117

### CODE REVIEW

**Review by oliverchang — COMMENTED** [review]
thanks Adrian! can you please fix the lint errors that our CI is pointing out?

**Comment by adetaylor** [comment]
Yep, I will do

**Comment by adetaylor** [comment]
Sorry for all the fiddly commits here - I can't get `butler.py` to run locally due to a failure in `install_deps.sh`.

**Comment by adetaylor** [comment]
Ugh, fixing these things is really time-consuming without the ability to run local tests or lints, so I'm going to stop for now. My next step will probably be to try to figure out why I can't run `install_deps.bash` reliably.

**Comment by davfu1** [comment]
Hey Adrian, I posted about my own issue with `install_deps.bash` here - see if it might be the same you're experiencing: https://github.com/google/clusterfuzz/issues/2952

**Comment by oliverchang** [comment]
Hey Adrian, coudl you please check if you still run into that after https://github.com/google/clusterfuzz/commit/4af2b87e3fc336233d8829fccacbb840d68d30a5 ?

**Comment by adetaylor** [comment]
Yep. I'm on vacation right now but I'll try it out when I return.

**Comment by adetaylor** [comment]
Let me know if you'd like me to rebase/squash this instead of using merges.

**Review by oliverchang — APPROVED** [review]
thanks!

**Pull request merged**
