### PR TITLE
Fix an exception when running Antlr under Python 3.

### PR DESCRIPTION
**Pull request by mbarbella-chromium**
Mitchel, would you mind taking a look at this? I think we may have had some other check in place to deal with Antlr failing to handle invalid utf-8, but this seems like a cleaner way to handle it which also fixes an issue we're seeing when running with Python 3. If there was another check, I'd like to remove it.

### CODE REVIEW

**Comment by mbarbella-chromium** [comment]
Thanks for the feedback. I switched the new check to return an AntlrDecodeError so that the existing fallbacks for line minimization should still work, and removed the old places where it was returned.

**Comment by mbarbella-chromium** [comment]
TBR. The Travis failures are a bunch of python 3 lint errors that would be better to clean up in another change, since this is already larger than I planned.

**Comment by inferno-chromium** [comment]
@oliverchang - can you do a review pass please.

**Pull request merged**
