### PR TITLE
Docs: Document FUZZ_TARGET_BUILD_BUCKET_PATH

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fixes https://github.com/google/clusterfuzz/issues/799.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
This is wrong description, we will update it sometime in near future.

**Comment by tapaswenipathak** [comment]
What?! Nothing is wrong in the doc. Can you tag the ticket internal? Suggesting a good read for you - https://opensource.guide/best-practices/.

**Comment by tapaswenipathak** [comment]
The doc is ok, I don't think anything is wrong in the doc, might be few enhancements required. 

Can you tag the ticket internal?  Closing PRs without informing what's wrong is inappropriate behavior for open source maintainers. Writing because you have done the same with two more prs. Might be a good read - https://opensource.guide/best-practices/.

**Comment by inferno-chromium** [comment]
FUZZ_TARGET_BUILD_BUCKET_PATH is not part of project setup, it is an attribute of Job definition and should be mentioned in the jobs description. Also, there is no MockConfig. Other than that, we need to mention targets.list file from which %TARGET% is derived.

**Pull request closed without merging**
