### PR TITLE
Support SUMMARY_PREFIX_SEPARATOR.

### LINKED ISSUE #792: Support custom fuzz target separators in issue titles
Right now, in our issue titles, we have the following format:

```
prefix/target_name: Crash in ....
```

The separator '/' should be customisable.

### PR DESCRIPTION
**Pull request by oliverchang**
Fixes #792.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@oliverchang - ideally if we can use a generic seperator instead of / that works for all, i would prefer to change to that, than reading another env var / iterating through job entity (can become expensive).

**Comment by oliverchang** [comment]
> @oliverchang - ideally if we can use a generic seperator instead of / that works for all, i would prefer to change to that, than reading another env var / iterating through job entity (can become expensive).

Yeah, I'm not too thrilled about adding yet another var either. What do you think about using ':' for everything?

**Comment by inferno-chromium** [comment]
Yes colon : sounds good everywhere

**Pull request closed without merging**
