### PR TITLE
Clear all persistent cache values when clearing data dirs.

### LINKED ISSUE #903: fuzzer-common-data-bundles is not accessible
```
fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-high-end-b1b2-3/clusterfuzz/bot/inputs/fuzzer-common-data-bundles/WebKit/JSTests'
```

same error for other data bundles, e.g. spidermonkey

### PR DESCRIPTION
**Pull request by oliverchang**
Fixes #903.

### CODE REVIEW

**Comment by oliverchang** [comment]
merging to fix exceptions.

**Comment by inferno-chromium** [comment]
Can you please explain why we keep persist files ?

**Comment by oliverchang** [comment]
> Can you please explain why we keep persist files ?

Because those indicate values that survive across reboots. clear_values() is called on startup.

**Comment by inferno-chromium** [comment]
> > Can you please explain why we keep persist files ?
> 
> Because those indicate values that survive across reboots. clear_values() is called on startup.

ah right, remember now, ah, so clear_values wasn't clearing all, yikes!

**Pull request merged**
