### PR TITLE
Remove dependency on blobstore (#403).

### PR DESCRIPTION
**Pull request by oliverchang**
Handle the upload ourselves instead of using the blobstore upload
handler.

### CODE REVIEW

**Comment by oliverchang** [comment]
Thanks! Note that this introduces a 32MB upload limit (App Engine limit) for uploads via this API endpoint. This keeps the implementation simple for us, without requiring changes in the clients. Will confirm with the relevant users of this to ensure that this seems enough before merging.

**Comment by inferno-chromium** [comment]
Yes that sounds good for now. Once we move to Appengine Flex, we won't run into urlfetch and other limits i think.

**Pull request merged**
