### PR TITLE
Corpus backup task: silently skip outdated fuzz targets (#907).

### PR DESCRIPTION
**Pull request by Dor1s**
I think we can make it a warning, but I'd prefer to figure out why the issue is happening in the first place. Maybe there is some other issue which we can fix and avoid these confusing failures across multiple cron tasks. This should help us to track down the root cause.

### CODE REVIEW

**Comment by mbarbella-chromium** [comment]
> If no one else is worried about this, I can add a `if not fuzz_target` check in the corpus backup task to skip such instances.

I'm not too worried about these cases in general so avoiding this change and checking it there sounds better to me. I don't feel too strongly if anyone else has an opinion.

**Comment by oliverchang** [comment]
> > If no one else is worried about this, I can add a `if not fuzz_target` check in the corpus backup task to skip such instances.
> 
> I'm not too worried about these cases in general so avoiding this change and checking it there sounds better to me. I don't feel too strongly if anyone else has an opinion.

That also sounds better to me.

**Comment by Dor1s** [comment]
Thanks! I changed the CL as discussed above. PTAL :)

**Pull request merged**
