### PR TITLE
Deprecated references and behaviors associated with ANDROID_EMULATOR.

### PR DESCRIPTION
**Pull request by davfu1**
ANDROID_EMULATOR was an enum originally created to enable fuzzing of TrustyOS on Android emulators. This is no longer needed as Trusty fuzzing has moved to on-device, and so this PR aims to clean up code specific to these now unmaintained emulators. 

The enum ANDROID_EMULATOR, however, remains associated and in use with Trusty fuzzers and is not removed here (it may need to be renamed, after considering all config files, in a later PR).

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]
thanks!

**Comment by oliverchang** [comment]
Can you please fix the lint errors pointed out in https://github.com/google/clusterfuzz/actions/runs/3500921715/jobs/5880060303 ?

**Comment by davfu1** [comment]
> Can you please fix the lint errors pointed out in https://github.com/google/clusterfuzz/actions/runs/3500921715/jobs/5880060303 ?

No problem Oliver - these lint errors should be fixed now in the latest commit.

**Comment by davfu1** [comment]
> Can you please fix the lint errors pointed out in https://github.com/google/clusterfuzz/actions/runs/3500921715/jobs/5880060303 ?

Thanks Oliver - the latest commits should have addressed these lint errors.

**Pull request merged**
