### PR TITLE
Delete corpus tagging

### PR DESCRIPTION
**Pull request by jonathanmetzman**
It's not really used and complicates the rearchitecture. 
Related: https://github.com/google/clusterfuzz/issues/3008
I do think it would be interesting to use though.

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
not sure if last fail was spurious.

**Comment by jonathanmetzman** [comment]
This error looks non trivial to fix sadly

**Comment by oliverchang** [comment]
> This error looks non trivial to fix sadly

Hmm, I've seen that particular test flake occassionally. I don't think you've changed any of the behaviour it's testing?

**Comment by jonathanmetzman** [comment]
> > This error looks non trivial to fix sadly
> 
> Hmm, I've seen that particular test flake occassionally. I don't think you've changed any of the behaviour it's testing?

Not sure about that, from a cursory look yesterday I think it was going to pollinate one way but now differently because of my change.

**Comment by oliverchang** [comment]
> > > This error looks non trivial to fix sadly
> > 
> > 
> > Hmm, I've seen that particular test flake occassionally. I don't think you've changed any of the behaviour it's testing?
> 
> Not sure about that, from a cursory look yesterday I think it was going to pollinate one way but now differently because of my change.

I think the test is unrelated -- it's testing that we properly report crashes in the corpora during pruning.

**Comment by oliverchang** [comment]
Hmm, the past few runs are still consistently failing though. Maybe something subtlely changed here.

**Comment by oliverchang** [comment]
I suspect there's an exception introduced here somewhere that prevents this from being run: https://github.com/google/clusterfuzz/blob/ba9b7699b05e540bfb84ba5abb73856d8bc27107/src/clusterfuzz/_internal/bot/tasks/corpus_pruning_task.py#L914

This is all wrapped in a try/catch, so it could be we have an exception happening before ` _process_corpus_crashes` is called (which is what the failing test is testing).

**Comment by oliverchang** [comment]
I was right. I pushed https://github.com/google/clusterfuzz/pull/3014/commits/215ab9f7c30b76ccce1814759c1dfdedd5dfc16c to your branch to remove the try/catch, and now the error is:

```
	status = StatusCode.UNKNOWN
	details = "Traceback (most recent call last):
  File "/workspace/src/clusterfuzz/_internal/bot/untrusted_runner/untrusted.py", line 80, in wrapper
    result = func(self, request, context)
  File "/workspace/src/clusterfuzz/_internal/bot/untrusted_runner/untrusted.py", line 186, in PruneCorpus
    return tasks_impl.prune_corpus(request, context)
  File "/workspace/src/clusterfuzz/_internal/bot/untrusted_runner/tasks_impl.py", line 59, in prune_corpus
    method=result.cross_pollination_stats.method,
AttributeError: 'CrossPollinationStats' object has no attribute 'method'
```

**Comment by jonathanmetzman** [comment]
Saving the corpus tags we already have in case we want them back:
```
libFuzzer_pdfium_xfa_lpm_fuzzer pdf
libFuzzer_gpu_angle_fuzzer      gpu
libFuzzer_aec3_config_json_fuzzer       json
libFuzzer_jsoncpp_fuzzer        json
libFuzzer_gpu_swiftshader_fuzzer        gpu
libFuzzer_libpng_read_fuzzer    png_decode
libFuzzer_pdfium_fuzzer pdf
libFuzzer_base_json_reader_fuzzer       json
libFuzzer_base_json_correctness_fuzzer  json
libFuzzer_xml_parser_fuzzer     xml
libFuzzer_libxml_xml_read_memory_fuzzer xml
libFuzzer_skia_skjson_fuzzer    json
libFuzzer_libjingle_xmpp_xmlparser_fuzzer       xml
libFuzzer_gpu_fuzzer    gpu
libFuzzer_gfx_png_image_fuzzer  png_decode
libFuzzer_json_web_key_fuzzer   json
libFuzzer_blink_png_decoder_fuzzer      png_decode
libFuzzer_gpu_raster_swiftshader_fuzzer gpu
libFuzzer_gpu_raster_fuzzer     gpu
libFuzzer_gpu_raster_angle_fuzzer       gpu
libFuzzer_pdf_codec_png_fuzzer  png_decode
libFuzzer_blink_json_parser_fuzzer      json
libFuzzer_expat_xml_parse_fuzzer        xml
libFuzzer_pdf_xml_fuzzer        xml
libFuzzer_v8_json_parser_fuzzer json
libFuzzer_gpu_raster_passthrough_fuzzer gpu
libFuzzer_devtools_protocol_encoding_json_fuzzer        json
libFuzzer_libpng_progressive_read_fuzzer        png_decode
libFuzzer_gpu_angle_passthrough_fuzzer  gpu
libFuzzer_pdfium_xfa_fuzzer     pdf
libFuzzer_grpc_json_fuzzer      json
```

**Pull request merged**
