### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sai-Adarsh**
Updates README.md, solves #168 by adding more links on fuzzing resources in documentation.

### CODE REVIEW

**Comment by Sai-Adarsh** [comment]
@inferno-chromium could you review the PR for the issue #168

**Comment by Sai-Adarsh** [comment]
@oliverchang could you review the PR for the issue #168

**Comment by HiZhaoxiaoyang** [comment]
i do remember this trick "all your base are belong to us"

**Comment by inferno-chromium** [comment]
This PR is not linking to fuzzing documentation, but just points to our open sourcing blog post. What we meant by #168 is to point to read world tutorials / examples of fuzzing that a beginner can use to know what fuzzing is.

**Pull request closed without merging**
