### PR TITLE
Upgrade all Docker images to latest.

### PR DESCRIPTION
**Pull request by oliverchang**
Un-pin from the Xenial revision.

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]
That is much simpler than I thought : )

**Comment by oliverchang** [comment]
> That is much simpler than I thought : )

This is only the first part :) Once they're built, we need to upgrade our configs to roll it out and make sure nothing breaks.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
