### PR TITLE
[zip] Favor fileobj over filepath

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I think this needs tests and to provide the same behavior for .tar.gz. Paul could you add those once this lands?

**Comment by jonathanmetzman** [comment]
We also can't accept zip files that aren't meant to be tested independently. Unsure if this fixes that.

**Comment by jonathanmetzman** [comment]
On second thought I don't think we can improve the velocity at which we merge commits from Chrome fuzzing if I spend so much time fixing issues with them. @paulsemel Can you please take over this CL from me?

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
I merged this since Paul is OOO and someone is blocked now.

**Pull request merged**
