### PR TITLE
Upgrade libraries.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
TBR

**Comment by inferno-chromium** [comment]
LGTM, can you fix pycrypto in docker/ci/requirements.txt as well ?

**Comment by oliverchang** [comment]
We are already on the latest version of pycrypto.

**Comment by alex** [comment]
What is clusterfuzz using pycrypto for, it'd be nice to remove it.

**Comment by oliverchang** [comment]
Good question. It might not be used anymore. Filed https://github.com/google/clusterfuzz/issues/159, thanks!

**Pull request merged**
