### PR TITLE
Log changes to environment variables.

### PR DESCRIPTION
**Pull request by letitz**
This should help debug ClusterFuzz issues in production.

### CODE REVIEW

**Comment by letitz** [comment]
This is a bit of a silly idea, but I thought I would throw it out for consideration. It might result in a crazy amount of log spam, though we could downgrade the log level to `DEBUG` to help with filtering (not sure how that interacts with GCP logging).

Another approach I could see would be to bundle up the current set of environment variables in the log `extras`.

WDYT?

**Comment by jonathanmetzman** [comment]
Both of these seem very spammy to be honest.

**Comment by letitz** [comment]
Would this be more palatable as `DEBUG` logs?

**Comment by jonathanmetzman** [comment]
OK so looking at this particular case. That build 88437 is an empty zip. So maybe we could add logging in setup_regular_build or elsewhere that 1. logs when the build is missing the APP_NAME. 2. Marks the build as a bad build.

**Comment by letitz** [comment]
I've got 1) covered by #3476. I can send another PR to have the setup code return a uworker error in these cases, and then mark the build as bad in that error's handler.

**Pull request closed without merging**
