### PR TITLE
Remove Auto-CC limit from .owners file.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
/gcbrun. We got a request from an internal team on this. I'm not sure what the motivation for this was (@jonathanmetzman I think you added/bumped this back in 2018 -- was it noise?), but it seems fine to me to not have this limit.

**Review by inferno-chromium — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
> /gcbrun. We got a request from an internal team on this. I'm not sure what the motivation for this was (@jonathanmetzman I think you added/bumped this back in 2018 -- was it noise?), but it seems fine to me to not have this limit.

Can't remember. Is it because in chrome (not OS) there are too many owners?

**Comment by jonathanmetzman** [comment]
Right, I think I bumped it up to 5 because chromeos asked for this.
The bug where I discussed this is https://bugs.chromium.org/p/chromium/issues/detail?id=905414
@inferno-chromium any chance you remember why we decided to leave it at 5?

**Comment by inferno-chromium** [comment]
> Right, I think I bumped it up to 5 because chromeos asked for this.
> The bug where I discussed this is https://bugs.chromium.org/p/chromium/issues/detail?id=905414'
> It only says I wanted to bump this but not why we decided not to cap it.
> @inferno-chromium any chance you remember why we decided to leave it at 5?

dont remember, limit seems ok to remove.

**Pull request merged**
