### PR TITLE
Simplify tensorflow Pipfile dependency.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
@Dor1s this seems to work. Any reason why you went with the wheel approach?

**Comment by oliverchang** [comment]
TBRing

**Comment by Dor1s** [comment]
my bad, #1588 is unrelated (it was inside docker), maybe https://github.com/google/clusterfuzz/pull/1623 fixed the problem then

Just verified that it works on my machine too, thanks a lot Oliver!

**Pull request merged**
