### PR TITLE
Show total fuzzing time instead of runs count in stats.

### LINKED ISSUE #937: Show time executed / cpu hours instead of number of runs in fuzzer stats.

### PR DESCRIPTION
**Pull request by inferno-chromium**
Fixes #937.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Ping to do this in OSS-Fuzz as well.

**Comment by jonathanmetzman** [comment]
Why not name this cpu_hours? I think it conveys the same thing without taking up precious screen real estate

**Comment by jonathanmetzman** [comment]
Actually, it seems done already in oss-fuzz. I think the old version is still showing up because of caching (compare https://oss-fuzz.com/fuzzer-stats/by-fuzzer/date-start/2019-08-29/date-end/2019-09-04/fuzzer/libFuzzer/job/libfuzzer_asan_aspell to https://oss-fuzz.com/fuzzer-stats/by-day/date-start/2019-08-29/date-end/2019-09-04/fuzzer/libFuzzer/job/libfuzzer_asan_aspell)

**Comment by inferno-chromium** [comment]
> Why not name this cpu_hours? I think it conveys the same thing without taking up precious screen real estate

We can change stat name for OSS-Fuzz (in db), but for general clusterfuzz case, it seems wrong to say cpu hours, without actually accounting for number of cpus that it is run on. we should probably enable fork mode always - https://github.com/google/clusterfuzz/issues/621, then change timeexecuted=timeexecuted*no of cpus. Unsure, how can we do this across every fuzzing engine.

**Comment by inferno-chromium** [comment]
> Actually, it seems done already in oss-fuzz. I think the old version is still showing up because of caching (compare https://oss-fuzz.com/fuzzer-stats/by-fuzzer/date-start/2019-08-29/date-end/2019-09-04/fuzzer/libFuzzer/job/libfuzzer_asan_aspell to https://oss-fuzz.com/fuzzer-stats/by-day/date-start/2019-08-29/date-end/2019-09-04/fuzzer/libFuzzer/job/libfuzzer_asan_aspell). Good change!

Yes if entity already exists, it needs to be manually updated everywhere. i did the change on all db across all project types. if we want to remove old results, we can clear memcache, but i feel it was ok.

**Comment by jonathanmetzman** [comment]
> > Why not name this cpu_hours? I think it conveys the same thing without taking up precious screen real estate
> 
> We can change stat name for OSS-Fuzz (in db), but for general clusterfuzz case, it seems wrong to say cpu hours, without actually accounting for number of cpus that it is run on. we should probably enable fork mode always - #621, then change timeexecuted=timeexecuted*no of cpus. Unsure, how can we do this across every fuzzing engine.

Ah very good point!

**Pull request merged**
