### PR TITLE
Convert RNN generation to TF v2.

### PR DESCRIPTION
**Pull request by mihaimaruseac**
TF v2 offers ways to handle validation and TensorBoard during model callback. We can also do the batching using `tf.data` instead of writing the loop manually.

I'm trying it this way now to not do too many changes at once but will probably send another PR later to convert to the recommended way.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Fixes #1540

**Comment by mihaimaruseac** [comment]
The pylint issue on Travis I think can be fixed by https://github.com/PyCQA/pylint/issues/1542#issuecomment-332505830. TensorBoard recommends the `as_default()` syntax in [the migration guide](https://www.tensorflow.org/tensorboard/migrate)

I cannot see the GCP build log so I don't know what failed there.

Should I instead try and convert code to use `tf.data` and callbacks for validation?

**Comment by mihaimaruseac** [comment]
I disabled it inline, hopefully this would fix the travis build

**Comment by mihaimaruseac** [comment]
Ok, Travis passes now. Should we try another /gcbrun ?

**Comment by mihaimaruseac** [comment]
Still fails :( But I cannot see the log

**Comment by inferno-chromium** [comment]
> Still fails :( But I cannot see the log

```
======================================================================
FAIL: test_train_rnn (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test train RNN model on a simple corpus.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/src/python/tests/core/bot/tasks/ml_train_task_test.py", line 193, in test_train_rnn
    self.assertTrue(ml_train_task.get_last_saved_model(self.model_directory))
AssertionError: {} is not true

----------------------------------------------------------------------
Ran 155 tests in 30.966s

FAILED (failures=1, skipped=4)

Ran 1437 tests (111 skipped, 0 errors, 1 failures).
```

**Comment by inferno-chromium** [comment]
> > Still fails :( But I cannot see the log
> 
> ```
> ======================================================================
> FAIL: test_train_rnn (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
> Test train RNN model on a simple corpus.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/workspace/src/python/tests/core/bot/tasks/ml_train_task_test.py", line 193, in test_train_rnn
>     self.assertTrue(ml_train_task.get_last_saved_model(self.model_directory))
> AssertionError: {} is not true
> 
> ----------------------------------------------------------------------
> Ran 155 tests in 30.966s
> 
> FAILED (failures=1, skipped=4)
> 
> Ran 1437 tests (111 skipped, 0 errors, 1 failures).
> ```

Using `python butler.py py_unittest -t core -m`

**Comment by mihaimaruseac** [comment]
Thanks. I'll try to replicate locally, it's possible to be caused by the change in model format

**Comment by Dor1s** [comment]
We can merge this today, but if anyone deploys, I won't be able to monitor the errors as I'm OOO today.

**Comment by mihaimaruseac** [comment]
I'm ok with waiting :)

**Pull request merged**
