### PR TITLE
Set Collaborator/ IAL When Creating Security Bugs

### PR DESCRIPTION
**Pull request by micahbales**
Now that we have added collaborators and issue_access_level to Issue in https://github.com/google/clusterfuzz/pull/3432 and https://github.com/google/clusterfuzz/pull/3437, this PR implements the Google Issue Tracker security flow for when bugs are filed that need to be reviewed by Chrome Security. This implementation depends on the 'Type-Security-Bug' label being set in the yaml config.

### CODE REVIEW

**Comment by micahbales** [comment]
@oliverchang This is a follow-on to https://github.com/google/clusterfuzz/pull/3432 and https://github.com/google/clusterfuzz/pull/3437

**Review by oliverchang — COMMENTED** [review]
Thanks! Please see https://github.com/google/clusterfuzz/pull/3432#issuecomment-1769933412 :)

**Comment by micahbales** [comment]
Not sure what this error is, which is causing All-Tests to fail

Screenshot 2023-10-19 at 4 04 41 PM

**Comment by jonathanmetzman** [comment]
You should have access now. Can you try again?

**Comment by micahbales** [comment]
Obviated by https://github.com/google/clusterfuzz/pull/3442

**Pull request closed without merging**
