### PR TITLE
Add dependabot config.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

Thanks!

**Comment by jonathanmetzman** [comment]
Related: https://github.com/google/clusterfuzz/issues/2564

**Review by Alan32Liu — APPROVED** [review]
LGTM!

**Comment by jonathanmetzman** [comment]
Is this missing the docs/ folder which has ruby packages? Or do we not care since it isn't production code?

**Comment by jonathanmetzman** [comment]
Also what about the dependencies of our front end code? Bower etc.

**Comment by oliverchang** [comment]
docs/ isn't as high priority as you mention, but we can certainly add it. 

Our bower stuff is also in a weird state since Bower is kind of dead and we should migrate to npm/package.json instead. We can address that then.

**Pull request merged**
