### PR TITLE
Fix exception due to resources/fuchsia removal

### PR DESCRIPTION
**Pull request by inferno-chromium**
Git does not allow empty dir, so need to create intermediates
bot/resources/fuchsia after
https://github.com/google/clusterfuzz/pull/486

### CODE REVIEW

**Comment by inferno-chromium** [comment]
i confused CI failure, which was legit. basically removing bot/resources/fuchsia/README.md removes resources/fuchsia subdir completely. so needs to create intermediates.

**Comment by inferno-chromium** [comment]
TBR, passes on gcb

**Comment by flowerhack** [comment]
oh gosh, i had thought `recreate=True` would handle this case. my bad! thanks for the fix

**Pull request merged**
