### PR TITLE
[Corpus Pruning] Move to preprocess_update_fuzzer_and_data_bundles to…

### PR DESCRIPTION
**Pull request by alhijazi**
… utask_preprocess

### CODE REVIEW

**Review by jonathanmetzman — COMMENTED** [review]
Fix test failure please.

**Comment by jonathanmetzman** [comment]
The fix might be here: https://github.com/google/clusterfuzz/pull/3355/files#diff-d5173931ea27c05bd2edb5c8e289f0fcd8c0415f30bd2ac5f6f7913735f74c04L26

**Comment by alhijazi** [comment]
> Fix test failure please.

Done

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
