### PR TITLE
Remove buggy associate_testcase_with_existing_issue_if_needed

### PR DESCRIPTION
**Pull request by inferno-chromium**
This is not working as expected and causing spam with multiple comments on bugs e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9575. Removing until furthur analysis.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Sorry wrong reviewer. Will TBR to avoid "reproducible variant errors".

**Comment by inferno-chromium** [comment]
TBR

**Comment by oliverchang** [comment]
LGTM

**Pull request merged**
