### PR TITLE
Delete dictionary analysis

### PR DESCRIPTION
**Pull request by jonathanmetzman**
It's not clear it delivers value, it does deliver complexity and would be too hard to support under the new architecture.
Related: https://github.com/google/clusterfuzz/issues/3008

### CODE REVIEW

**Comment by oliverchang** [comment]
Big +1 to this!

**Comment by jonathanmetzman** [comment]
Fixes: https://github.com/google/clusterfuzz/issues/3009

**Comment by jonathanmetzman** [comment]
Test fail looks spurious. Trying again

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
