### PR TITLE
add new AFL++ features

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This activates command line features introduced in oss-fuzz's AFL++ update in June.
It also adds an important env vars (AFL_IGNORE_SEED_PROBLEMS which will prevent aborted startups in the CI).

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
can you run `python butler.py format` (in the virtualenv) please?

**Comment by vanhauser-thc** [comment]
done

**Comment by jonathanmetzman** [comment]
I think you need to run it again.
Also should run `python butler.py lint` to get that out of the way.

**Comment by vanhauser-thc** [comment]
I think now it is done :)

**Comment by jonathanmetzman** [comment]
It's still complaining. Can you post the output of your command? https://github.com/google/clusterfuzz/actions/runs/6160096848/job/16716262177?pr=3326

**Comment by vanhauser-thc** [comment]
this is super difficult for me. clusterfuzz only supports outdated python which I do not have on my system. so I try to solve this with an ubuntu 20.04 docker container where I mount that in, but then I get a git error about FETCH_HEAD I cannot resolve after spending an hour of time. so I analyze what python stuff butler.py is doing and executing the corresponding commands. (again needing the container because ypf3 errors on my system). 

also the lines that are marked as wrongly formatted are not any I have touched in this PR (on any previous one).

also why did my ypf3 not do these formattings? My guess it is a version difference.

**Comment by vanhauser-thc** [comment]
tried to fix it by hand from the CI ...

**Comment by jonathanmetzman** [comment]
> this is super difficult for me. clusterfuzz only supports outdated python which I do not have on my system. so I try to solve this with an ubuntu 20.04 docker container where I mount that in, but then I get a git error about FETCH_HEAD I cannot resolve after spending an hour of time. so I analyze what python stuff butler.py is doing and executing the corresponding commands. (again needing the container because ypf3 errors on my system).
> 
> also why did my ypf3 not do these formattings? My guess it is a version difference.

Ugh sorry about that, I think different yapfs versions format differently. I'm hoping to update python versions in the next month or two.

**Comment by jonathanmetzman** [comment]
Can I merge this now or do I need to wait for the oss-fuzz changes to land?

**Comment by vanhauser-thc** [comment]
This can be merged now. The functionality that would break if afl-fuzz doesn’t know the parameter was added to oss-fuzz in June

**Pull request merged**
