### PR TITLE
Move fuzz target chmod to somewhere more general.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
TBR to fix issues. Some build archives may have executables with the execute bit set.

**Comment by inferno-chromium** [comment]
LGTM

**Comment by Dor1s** [comment]
@oliverchang do you think the Travis failure has anything to do with your change?

**Comment by oliverchang** [comment]
weird, travis tests should be a subset of container builder tests, which are passing. i'll take a look.

**Pull request merged**
