### PR TITLE
Use Python 2 for blackbox launchers.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
afl is still using Python 3, as the launcher.py for that comes in via APP_NAME and not Fuzzer.launcher_path.

**Comment by inferno-chromium** [comment]
But AFL's launcher.py should Py3 compatible, and shouldn't we run this in python 3 ?

**Comment by oliverchang** [comment]
> But AFL's launcher.py should Py3 compatible, and shouldn't we run this in python 3 ?

Yes, that's exactly the case even after this PR :)

**Comment by inferno-chromium** [comment]
oh right right, looked at it now more closely this is about general launchers. and then it is still based on sys.executable. Thanks for fix.
LGTM!

**Pull request merged**
