### PR TITLE
Move substitution lower down

### PR DESCRIPTION
**Pull request by rmistry**
https://team.git.corp.google.com/v8-team/autozilli/+/refs/heads/main/FuzzilliModules/ClusterfuzzUploader.swift#178

### CODE REVIEW

**Comment by rmistry** [comment]
PTAL @jonathanmetzman 
CC @micahbales

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Comment by rmistry** [comment]
All checks have passed. @jonathanmetzman please merge and deploy when you can

**Pull request merged**
