### PR TITLE
Fix formatting issues in https://github.com/google/clusterfuzz/pull/2614

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
@jonathanmetzman can you help with fixing the lint issues?

**Comment by jonathanmetzman** [comment]
What's very odd is I'm not getting these linting failures locally.
I suspect the version of my pylint is different somehow.

**Comment by jonathanmetzman** [comment]
For some reason my pylint version is 2.12.2 even though it's 2.4 in Pipfile

**Pull request closed without merging**
