### PR TITLE
Convert to TF v2 model

### PR DESCRIPTION
**Pull request by mihaimaruseac**
I had to change batch size: now it must be the same as when the model was created. I think there might a possibility to use a different batch size but I'll have to look through documentation to make sure.

Also, changed a typo: first argument of build_model should be the product between hidden layer size and hidden state size, not the square of one of the sizes. Again, this should match the model as trained.

Finally, changed the error type that is thrown when trying to predict using a model of invalid format.

The rest, is just moving stuff outside of the session loop and replacing the feed+run with a direct model call to get the prediction.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Can you 'git pull' and 'git rebase' to tip of tree trunk, unsure why those lint error show up in unrelated files.

**Comment by mihaimaruseac** [comment]
Rebased now, though now this required changing base to `master` and now this PR includes the commit from #2067. So CLA check now requires Max to agree with this PR too

**Comment by mihaimaruseac** [comment]
Ok, Pylint fixed, not all that's left is the CLA from Max and the other CI action

**Comment by inferno-chromium** [comment]
Can you please check the test failures

```
======================================================================
FAIL: test_empty_corpus (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test generation should abort for empty corpus.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 89, in test_empty_corpus
    self.assertEqual(result.return_code, constants.ExitCode.CORPUS_TOO_SMALL)
AssertionError: 1 != 2

======================================================================
FAIL: test_generate (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test generate specified number of inputs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 68, in test_generate
    self.assertEqual(result.return_code, constants.ExitCode.SUCCESS)
AssertionError: 1 != 0

======================================================================
FAIL: test_invalid_model (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test TensorFlow should throw exception if model does not match.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 114, in test_invalid_model
    self.assertEqual(result.return_code, constants.ExitCode.TENSORFLOW_ERROR)
AssertionError: 1 != 3

======================================================================
FAIL: test_timeout (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test timeout case in generation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 140, in test_timeout
    self.assertTrue(result.timed_out)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 196 tests in 105.692s

FAILED (failures=4, skipped=25)```

**Comment by inferno-chromium** [comment]
Max is OOO till tue, so i guess this will have to wait for wed/thu.

**Comment by mihaimaruseac** [comment]
It seems the failures are because model in `...src/python/tests/data/model/rnn` is invalid. Locally I don't have that at all, so probably we have some order dependent test? Which process generates that directory?

**Comment by Dor1s** [comment]
Thanks a lot @mihaimaruseac. I'll jump on this later this week when I get back to work!

**Comment by Dor1s** [comment]
> It seems the failures are because model in `...src/python/tests/data/model/rnn` is invalid. Locally I don't have that at all, so probably we have some order dependent test? Which process generates that directory?

those files are now in `src/python/tests/core/bot/fuzzers/ml/rnn/data/`

let me see what's up with the CLA

**Comment by Dor1s** [comment]
It looks like paths are correctly calculated in the `setUp` method inside `ml_rnn_generator_test.py`

**Comment by Dor1s** [comment]
I've been debugging `generate.py` script and found out that it fails on `model.load_weights(model_path)`

**Comment by Dor1s** [comment]
Here's what it says in the exception:

```
WARNING:tensorflow:From /home/mmoroz/.local/share/virtualenvs/clusterfuzz-YbspJ7qf/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py:1298: NameBasedSaverStatus.__init__ (from tensorflow.python.training.tracking.util) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "/home/mmoroz/projects/py3/clusterfuzz/src/python/bot/fuzzers/ml/rnn/generate.py", line 219, in <module>
    sys.exit(main(parsed_args))
  File "/home/mmoroz/projects/py3/clusterfuzz/src/python/bot/fuzzers/ml/rnn/generate.py", line 78, in main
    model.load_weights(model_path)
  File "/home/mmoroz/.local/share/virtualenvs/clusterfuzz-YbspJ7qf/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2193, in load_weights
    status.assert_nontrivial_match()
  File "/home/mmoroz/.local/share/virtualenvs/clusterfuzz-YbspJ7qf/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1006, in assert_nontrivial_match
    return self.assert_consumed()
  File "/home/mmoroz/.local/share/virtualenvs/clusterfuzz-YbspJ7qf/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 983, in assert_consumed
    "".join(unused_attribute_strings)))
AssertionError: Some objects had attributes which were not restored:
    <tf.Variable 'embedding/embeddings:0' shape=(256, 256) dtype=float32, numpy=
array([[-0.02241529, -0.0422815 , -0.02919068, ..., -0.03826899,
         0.02124007, -0.01377688],
       [ 0.02941957,  0.04020843, -0.0237347 , ..., -0.02090747,
         0.01928825, -0.01867964],
       [ 0.013739  ,  0.00338761, -0.00058122, ..., -0.00461984,
         0.03948903, -0.0156316 ],
       ...,
       [-0.01819172, -0.01343255, -0.01326929, ...,  0.00675465,
        -0.03513972,  0.03588214],
       [ 0.04508985, -0.04055017, -0.04738395, ...,  0.0028966 ,
        -0.01158311, -0.0337504 ],
       [-0.01969379, -0.01712549, -0.04147591, ..., -0.04328765,
        -0.03944162, -0.02184968]], dtype=float32)>: ['embedding/embeddings']
    <tf.Variable 'dense/kernel:0' shape=(2, 256) dtype=float32, numpy=
array([[-0.06997599, -0.13741557,  0.12453067,  0.02128063, -0.04478781,
         0.04930219,  0.13631293, -0.10299692,  0.00952381, -0.04473774,
        -0.04470004, -0.15121876, -0.092393  , -0.00535546, -0.12382267,
         0.08232453, -0.07540519,  0.12787378, -0.08058231,  0.05434623,
         0.086668  ,  0.08007689,  0.1521785 ,  0.00377437,  0.12385705,
        -0.03583395, -0.114253  ,  0.02303056,  0.05634651, -0.04131005,
         0.10051811, -0.04162593,  0.10434189, -0.04143217, -0.04844958,
        -0.11088249, -0.13839068,  0.0112218 ,  0.03383052,  0.14346975,
         0.03450327, -0.08577314, -0.0043215 , -0.02973735,  0.14756542,
        -0.15235877, -0.14929754, -0.14680578, -0.11469425,  0.14300606,
        -0.02026266,  0.13645363, -0.13366607, -0.1455758 , -0.11190879,
         0.01931515,  0.03271046, -0.09455819, -0.11854708, -0.02614391,
        -0.11210807,  0.09247376,  0.00343275,  0.01273777,  0.06361987,
         0.09222031,  0.06746475, -0.02662034,  0.0711953 ,  0.04393059,
         0.0292379 ,  0.05588119, -0.10228986, -0.14444579, -0.06401134,
         0.1075545 ,  0.02580191,  0.01592149, -0.00773913, -0.07810077,
         0.06138183,  0.01453093, -0.05821925,  0.00650322,  0.10315865,
         0.08783576, -0.02201016, -0.14641769, -0.1365056 , -0.01965132,
        -0.01815659, -0.02364302,  0.0723317 , -0.11047568, -0.06747322,
        -0.06124348,  0.03118207, -0.06058998, -0.05836574, -0.02932575,
         0.09296703,  0.01908275,  0.05726568,  0.0469182 , -0.03542662,
         0.05497019,  0.05937149,  0.00092158, -0.00074594, -0.13348523,
         0.12451854, -0.02017032, -0.05230708,  0.05379865, -0.12279565,
         0.05554251,  0.14342615,  0.03305852,  0.03936546,  0.01382419,
         0.06881332, -0.00786573, -0.02675636, -0.1326392 ,  0.13580623,
        -0.00142704,  0.0337313 ,  0.0137025 ,  0.03620593, -0.05336096,
         0.03973405, -0.07355007, -0.02746615,  0.12793097, -0.0787209 ,
        -0.11415258, -0.00176084, -0.14410816,  0.03307615,  0.13726798,
        -0.10059108,  0.04659832,  0.08861917,  0.02169167,  0.06641777,
         0.12316945, -0.02297065,  0.02890268,  0.1213147 ,  0.09310436,
        -0.02821335,  0.11329263, -0.03183211, -0.00084119,  0.00726072,
         0.02914053,  0.14015567,  0.06692442, -0.08587079,  0.09260024,
        -0.01329379,  0.05607934, -0.0673852 , -0.08445129,  0.0977537 ,
        -0.05985612, -0.02224652,  0.11043727,  0.08038902,  0.00769863,
         0.08149454,  0.14716828,  0.08255948,  0.09451437,  0.12021083,
         0.11654344,  0.14935923,  0.03199725,  0.13705736, -0.07815687,
        -0.09642658,  0.11881319, -0.10651329, -0.0977377 ,  0.06613202,
         0.11431548,  0.00158679, -0.01271383, -0.14326799, -0.10400783,
         0.02409856, -0.11829923, -0.14402184,  0.12412605, -0.14205307,
        -0.10331655,  0.1038757 , -0.02755138,  0.09279476, -0.08900723,
        -0.10017521,  0.13148183,  0.09378801, -0.02605943, -0.07782216,
        -0.10249645, -0.01060021,  0.15217319,  0.10025752, -0.11041166,
        -0.07758015, -0.09257927, -0.1362224 ,  0.14542699,  0.01614484,
         0.10160282,  0.11456528,  0.13153449, -0.1297007 ,  0.14729097,
         0.13207051, -0.01860261,  0.06988971, -0.11191544, -0.04829212,
        -0.13684762,  0.1302382 , -0.0359936 ,  0.03906479, -0.15056907,
        -0.08276022, -0.10583201,  0.12951607,  0.13571051,  0.06736702,
        -0.08274619, -0.09998146, -0.00700854, -0.03398436,  0.02898644,
         0.06006572, -0.04258194,  0.0476982 , -0.02301551, -0.06363787,
        -0.0800906 ,  0.02202888,  0.10121822, -0.05498917, -0.06866109,
        -0.04729836, -0.01197347,  0.11669877, -0.00170438, -0.01073678,
         0.10577959],
       [ 0.01265876,  0.0485584 ,  0.14889082, -0.12579152,  0.13805187,
         0.12810796, -0.04298501, -0.02381322, -0.09358018, -0.07034808,
         0.03236687, -0.1267709 ,  0.01727694, -0.10949971, -0.14131063,
        -0.01367734, -0.04503592, -0.1390588 , -0.01222402, -0.11221544,
         0.01685053,  0.00598788,  0.04359677, -0.02444778,  0.01601173,
        -0.0222214 , -0.13127851,  0.06133638, -0.03519905, -0.09368467,
        -0.05321171, -0.04262888, -0.04045195,  0.01094355,  0.09143801,
         0.11507693, -0.09664993,  0.00184414,  0.11366454, -0.12052575,
         0.10515732, -0.00797902,  0.02242036,  0.08274357, -0.07037172,
         0.02535997,  0.15212935,  0.14403173,  0.0569607 ,  0.13842562,
         0.11913875,  0.0207855 , -0.0041364 , -0.06277992,  0.10160148,
        -0.10988209,  0.03688395, -0.05651146,  0.12587515,  0.06130366,
         0.00650991, -0.11079607, -0.09180582, -0.05806095,  0.1342144 ,
        -0.03712191, -0.12172456,  0.03422886, -0.00877784, -0.14481747,
         0.06285602, -0.01144551,  0.00350744, -0.08789618, -0.09985907,
        -0.0733365 , -0.15082906,  0.1430712 ,  0.08942114, -0.02827036,
         0.00095862, -0.03946351,  0.00801051,  0.09549581, -0.09437407,
         0.04060455,  0.05296466,  0.13228738, -0.04755433, -0.06696028,
         0.07505967,  0.094652  , -0.09039307,  0.07295869, -0.08244354,
         0.1426048 ,  0.11823252, -0.06342503, -0.09119361,  0.02676091,
         0.04083484, -0.01344344, -0.12591481,  0.072855  , -0.13350664,
         0.14222115, -0.09017731,  0.13203198, -0.11287487, -0.07164456,
        -0.15043421, -0.01003321,  0.04916948,  0.01279379,  0.1180172 ,
         0.05349429, -0.03776757,  0.09063445,  0.1267404 , -0.07651434,
        -0.08612825,  0.00355756,  0.04033746,  0.1378209 ,  0.01320428,
         0.04822525, -0.04042952,  0.03236258, -0.05375229,  0.01854756,
        -0.02026117,  0.09746806,  0.02195224, -0.11887901, -0.01520312,
        -0.09681241, -0.14308968, -0.07186692, -0.08165154, -0.12877294,
         0.09725642, -0.02827168, -0.03068002,  0.13220605, -0.07045996,
        -0.09150505,  0.0691949 , -0.01973546,  0.05663751, -0.11958534,
         0.05527028, -0.03355027,  0.08753744,  0.11496884, -0.0110833 ,
        -0.02299845,  0.07370986, -0.10779791,  0.15062055,  0.11308974,
        -0.06646598, -0.09727558, -0.00185697, -0.03977194, -0.07556633,
         0.12804809,  0.09652606, -0.01997524, -0.11450046, -0.11754435,
        -0.11534441,  0.0285195 , -0.05842745, -0.0514473 , -0.13348636,
         0.0609929 ,  0.05965334,  0.05503331,  0.13862926, -0.12500541,
        -0.01840168, -0.00951923,  0.04435816, -0.00069489,  0.09488389,
        -0.041467  , -0.1077677 , -0.11902385,  0.09238446, -0.10706638,
         0.09041049,  0.05907735, -0.11671312, -0.1353927 , -0.04760534,
         0.03090988,  0.01781827, -0.05104714,  0.12034515, -0.0070931 ,
         0.15098777,  0.04796253,  0.13221967,  0.12694758, -0.04167531,
        -0.08324084,  0.08656491,  0.04732789,  0.07814418, -0.00241631,
         0.04550876, -0.088573  , -0.12137232, -0.09749348,  0.14708564,
        -0.13653275,  0.09900755,  0.14596555, -0.08313689, -0.01720814,
         0.12438807, -0.05524506,  0.14310354,  0.06787542,  0.07079828,
         0.12884307, -0.08886972,  0.03951186, -0.14287996,  0.07947908,
        -0.02999583, -0.00912863, -0.12784478, -0.08814397, -0.05257351,
         0.00348042, -0.10365479,  0.12166941, -0.0429296 , -0.06451753,
        -0.04978594,  0.09439141, -0.00277627, -0.11851455, -0.03557079,
        -0.1226957 , -0.08699595, -0.07930078, -0.02099666,  0.07420525,
        -0.06685909,  0.14699185, -0.07826395,  0.13831264, -0.06879979,
         0.12590861]], dtype=float32)>: ['dense/kernel']
    <tf.Variable 'dense/bias:0' shape=(256,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)>: ['dense/bias']
    <tf.Variable 'gru/gru_cell/kernel:0' shape=(256, 6) dtype=float32, numpy=
array([[-0.01121302,  0.11775003,  0.11448078,  0.13445969,  0.10704677,
        -0.02851631],
       [ 0.06922166,  0.02780157, -0.03203009, -0.00100663, -0.06249374,
        -0.0890875 ],
       [-0.09229294,  0.01227972,  0.00056879, -0.14026886,  0.03368291,
         0.09449418],
       ...,
       [ 0.00999366, -0.02703822, -0.12060309, -0.12329064,  0.10380591,
        -0.09652096],
       [ 0.01456571, -0.05960392,  0.0702678 ,  0.11490901, -0.01671264,
        -0.03092276],
       [-0.1318672 , -0.07402577,  0.06596498,  0.10589458, -0.09289482,
         0.14924769]], dtype=float32)>: ['gru/gru_cell/kernel']
    <tf.Variable 'gru/gru_cell/recurrent_kernel:0' shape=(2, 6) dtype=float32, numpy=
array([[ 0.5208285 , -0.6251771 ,  0.01364988,  0.4957772 ,  0.13757227,
         0.27015516],
       [ 0.26100853,  0.1950871 , -0.82470953, -0.24477543,  0.19985127,
         0.33736372]], dtype=float32)>: ['gru/gru_cell/recurrent_kernel']
    <tf.Variable 'gru/gru_cell/bias:0' shape=(2, 6) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>: ['gru/gru_cell/bias']
```

**Comment by mihaimaruseac** [comment]
I'll have to try to replicate the build environment and try training and testing there

**Comment by Dor1s** [comment]
> I'll have to try to replicate the build environment and try training and testing there

Let me first try to train a new model locally and see if the tests start to work from that point on.

**Comment by Dor1s** [comment]
> Let me first try to train a new model locally and see if the tests start to work from that point on.

Yep, the generate script starts to work if I pass a newer model to it! Now the problem I have is that the new model is too large for a test one: 35MB. That's comparable to what we had in production (both old and new model sizes), but for the test we somehow generated a tiny one (28KB). @mihaimaruseac are there any tricks for creating a dummy tiny model? I don't want to commit a 35MB file to the repo :)

**Comment by mihaimaruseac** [comment]
When you generated the model locally, did you pass different flags for the hidden layer size and hidden state size? Passing 2 and 2 for example should result in a tiny model.

We just need to ensure that the test uses the same arguments when loading the model.

**Comment by Dor1s** [comment]
Oh, I see, it comes from the hidden level and state size parameters. We used to pass them through the meta file, but now we should either use a constant size OR mock test values.

**Comment by Dor1s** [comment]
> Oh, I see, it comes from the hidden level and state size parameters. We used to pass them through the meta file, but now we should either use a constant size OR mock test values.

Yeah, I think I got it. Now need to clean up and update the PR. Hopefully that would make the CLA bot happy too.

Thanks a lot @mihaimaruseac for migrating the generation to the v2 API!

**Comment by Dor1s** [comment]
@googlebot I consent

**Review by Dor1s — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Thank you for pushing through to merge

**Pull request merged**
