### PR TITLE
Make dropdowns for project, fuzzer, job searchable.

### PR DESCRIPTION
**Pull request by inferno-chromium**
This adds a dedicated search box and allows searching for
sub-strings.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
> Looks good to me overall.
> 
> Is there a way to set a minimum width on the dropdown? Or maybe force the selection to be cleared if the user types something without a match? I noticed that if you type something with no match (consider a typo like tesst in one of the search boxes), then re-select the dropdown and correct it without fully clearing (backspace x2 in the previous example), you'll be left with a very narrow box that doesn't show the results well.

Cannot fix this yet, will do in another cl.

**Comment by inferno-chromium** [comment]
@oliverchang fyi!

**Comment by oliverchang** [comment]
awesome!!!

**Pull request merged**
