### PR TITLE
[AFL] AFL++ integration

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Superseeds: https://github.com/google/clusterfuzz/pull/2259

**Review by inferno-chromium — APPROVED** [review]

**Comment by oliverchang** [comment]
Nice! Just curious here: Is this integration compatible with previous vanilla AFL builds?

**Comment by vanhauser-thc** [comment]
@oliverchang yes you can keep old builds. but afl++ supports better instrumentation, especially for large targets, so rebuilding with afl-clang-fast from afl++ is recommended. note that oss-fuzz was moved to afl++ 8 weeks ago.

**Pull request merged**
