### PR TITLE
[DO NOT MERGE] Script to migrate incorrectly archived testcases

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I'm trying this out on one testcase.

**Comment by jonathanmetzman** [comment]
This shouldn't be used. Some testcases are genuinely archvied https://oss-fuzz.com/testcase-detail/4804684966068224

**Comment by jonathanmetzman** [comment]
Based on the logs, this seems to be working on https://oss-fuzz.com/testcase-detail/5175412550860800 https://pantheon.corp.google.com/logs/query;query=SEARCH%2528%225175412550860800%22%2529;cursorTimestamp=2024-08-16T00:21:02.926678176Z;duration=PT1H?e=-13802955&mods=logs_tg_prod&orgonly=true&project=clusterfuzz-external&supportedpurview=organizationId I will wait for this to complete to run it.

**Review by oliverchang — COMMENTED** [review]
nice, thanks!

**Pull request merged**
