### PR TITLE
Also install future in Windows startup script.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
Also, what's the proper way to install this on our macOS machines these days?

**Comment by inferno-chromium** [comment]
actually why do we need in startup script ? we have this src/requirements.txt for bots. do we have other scripts like docker ones that need future (e.g. https://github.com/google/clusterfuzz/commit/4bf86226113c2e862edee42574b2cf39264d661f)

**Comment by oliverchang** [comment]
This is just to make it safer to run the remainder of the fixers. For instance, I'm not even sure how https://github.com/google/clusterfuzz/blob/master/src/python/bot/startup/run_bot.py#L20 works right now, because it happens before the `modules.fix_module_search_paths()`, which is what adds `third_party` to `sys.path`.

**Comment by inferno-chromium** [comment]
ah right, i think all these builtins import should be moved after fix_module_search_paths for safety and to work across mac, android bots.

**Pull request merged**
