### PR TITLE
Fix base image build

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
This was why the bad deploy (leading to psutil not being found everywhere) happened.

**Comment by jonathanmetzman** [comment]
> This was why the bad deploy (leading to psutil not being found everywhere) happened.

The code was initially removed by me then added back but removed again during the 3.11->3.7 revert.

**Comment by jonathanmetzman** [comment]
TBR

**Review by oliverchang — COMMENTED** [review]
LGTM

**Pull request merged**
