### PR TITLE
Use sys.executable for invoking Python interpreter.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
How about these
```
src/python/bot/fuzzers/ml/rnn/generator.py:  rnn_runner = new_process.ProcessRunner('python')
src/python/bot/tasks/ml_train_task.py:  rnn_trainer = new_process.ProcessRunner('python')
```

I wonder how peach mutator is getting executed, it might explicitly need python2 somewhere - https://github.com/google/clusterfuzz/commit/32ce4d06bf75dabff18f009b5eacd3ae88e7fc51

**Comment by oliverchang** [comment]
> How about these
> 
> ```
> src/python/bot/fuzzers/ml/rnn/generator.py:  rnn_runner = new_process.ProcessRunner('python')
> src/python/bot/tasks/ml_train_task.py:  rnn_trainer = new_process.ProcessRunner('python')
> ```
> 
> I wonder how peach mutator is getting executed, it might explicitly need python2 somewhere - [32ce4d0](https://github.com/google/clusterfuzz/commit/32ce4d06bf75dabff18f009b5eacd3ae88e7fc51)

Done!

**Comment by oliverchang** [comment]
Re peach that's getting executed by libFuzzer via a custom mutator right? Are there any changes needed there? @mbarbella-chromium

**Comment by mbarbella-chromium** [comment]
Peach should be fine as-is. It doesn't invoke the python interpreter directly.

**Pull request merged**
