### PR TITLE
Centipede support custom asan options

### LINKED ISSUE #3133: Make Centipede handle custom ASAN options that libFuzzer supports
See https://bugs.chromium.org/p/chromium/issues/detail?id=1451080#c4

### PR DESCRIPTION
**Pull request by Alan32Liu**
Fix #3133.

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]

**Comment by Alan32Liu** [comment]
Trial build failed due to `HonggFuzz`:
```
======================================================================
FAIL: test_fuzz_netdriver_crash (tests.core.bot.fuzzers.honggfuzz.honggfuzz_engine_test.UnshareIntegrationTest)
Test netdriver fuzzing that results in a crash.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/src/clusterfuzz/_internal/tests/core/bot/fuzzers/honggfuzz/honggfuzz_engine_test.py", line 211, in test_fuzz_netdriver_crash
    self.assertEqual(b'B', f.read()[:1])
AssertionError: b'B' != b'b'

----------------------------------------------------------------------
Ran 227 tests in 182.650s

FAILED (failures=1, skipped=10)
```

**Comment by jonathanmetzman** [comment]
> Trial build failed due to `HonggFuzz`:
> 
> ```
> ======================================================================
> FAIL: test_fuzz_netdriver_crash (tests.core.bot.fuzzers.honggfuzz.honggfuzz_engine_test.UnshareIntegrationTest)
> Test netdriver fuzzing that results in a crash.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/workspace/src/clusterfuzz/_internal/tests/core/bot/fuzzers/honggfuzz/honggfuzz_engine_test.py", line 211, in test_fuzz_netdriver_crash
>     self.assertEqual(b'B', f.read()[:1])
> AssertionError: b'B' != b'b'
> 
> ----------------------------------------------------------------------
> Ran 227 tests in 182.650s
> 
> FAILED (failures=1, skipped=10)
> ```

I'm very close to deleting that test as it's broken deploy many times.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
> > Trial build failed due to `HonggFuzz`:
> > ```
> > ======================================================================
> > FAIL: test_fuzz_netdriver_crash (tests.core.bot.fuzzers.honggfuzz.honggfuzz_engine_test.UnshareIntegrationTest)
> > Test netdriver fuzzing that results in a crash.
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/workspace/src/clusterfuzz/_internal/tests/core/bot/fuzzers/honggfuzz/honggfuzz_engine_test.py", line 211, in test_fuzz_netdriver_crash
> >     self.assertEqual(b'B', f.read()[:1])
> > AssertionError: b'B' != b'b'
> > 
> > ----------------------------------------------------------------------
> > Ran 227 tests in 182.650s
> > 
> > FAILED (failures=1, skipped=10)
> > ```
> 
> I'd really like to delete or fix this, it's broken deploy many times.

Fixed here: https://github.com/google/clusterfuzz/pull/3145

**Comment by Alan32Liu** [comment]
Shall I deploy this, or are there any changes we'd like to wait for and delopy together?

**Comment by jonathanmetzman** [comment]
Yes go ahead!

**Comment by Alan32Liu** [comment]
> Yes go ahead!

Cool!
Just to double-check, is this the right command to deploy?
```
python butler.py deploy --config-dir=</abs/path/to/local/clusterfuzz-config/dir/>
```

**Comment by jonathanmetzman** [comment]
./deploy.sh is usually what I use, though it doesn't deploy to Google3

**Comment by jonathanmetzman** [comment]
in clusterfuzz-config.

**Comment by Alan32Liu** [comment]
OK I will use `./deploy.sh` in the future, then.

For some reason, I thought that was for deploying changes in the config 🤦🏼‍♂️

**Comment by Alan32Liu** [comment]
> I deployed

Thanks!

**Pull request merged**
