### PR TITLE
Speculative fix for fuzzer_and_job_weights exception.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
tbr

**Review by inferno-chromium — COMMENTED** [review]
dont understand this, but lets see how it goes.

**Comment by oliverchang** [comment]
> dont understand this, but lets see how it goes.

This can happen when columns are missing in the given time period for a fuzzer. The weight result from this query: https://github.com/google/clusterfuzz/blob/17dc87e1a41b5d2cffe7702d5528a18a50b42c33/src/appengine/handlers/cron/fuzzer_and_job_weights.py#L96 will be null in that case.

**Pull request merged**
