### PR TITLE
Add Android code source map

### PR DESCRIPTION
**Pull request by TheCoryBarker**
Adding new mapping for Android source code for link generation.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you run lint/format and make sure the tests pass?

**Review by Hamidvakil — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Do you want to add a test?

**Comment by TheCoryBarker** [comment]
Added a unit test

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
I'll try to merge this tomorrow or monday

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
