### PR TITLE
Fix access limits integration with issuetracker public API

### PR DESCRIPTION
**Pull request by rmistry**
Without these fixes this error shows up when communicating with public API locally:
```
Traceback (most recent call last):
  File "src/clusterfuzz/_internal/issue_management/google_issue_tracker/issue_tracker.py", line 709, in <module>
    issue.save(new_comment='testing')
  File "src/clusterfuzz/_internal/issue_management/google_issue_tracker/issue_tracker.py", line 406, in save
    self.issue_tracker.client.issues().create(
  File "/usr/local/google/home/rmistry/.local/share/virtualenvs/clusterfuzz--XR7raGU/lib/python3.8/site-packages/googleapiclient/discovery.py", line 1123, in method
    headers, params, query, body = model.request(
  File "/usr/local/google/home/rmistry/.local/share/virtualenvs/clusterfuzz--XR7raGU/lib/python3.8/site-packages/googleapiclient/model.py", line 160, in request
    body_value = self.serialize(body_value)
  File "/usr/local/google/home/rmistry/.local/share/virtualenvs/clusterfuzz--XR7raGU/lib/python3.8/site-packages/googleapiclient/model.py", line 273, in serialize
    return json.dumps(body_value)
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IssueAccessLevel is not JSON serializable

```

Local test steps have been documented in the `google_issue_tracker/issue_tracker.py` file.
An example of a successful issue created with collaborators and issue access limit is: b/307559515

### CODE REVIEW

**Comment by rmistry** [comment]
@oliverchang PTAL.

CC @jonathanmetzman and @micahbales

**Comment by rmistry** [comment]
Looks like all checks are passing. Needs one reviewer approval now.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
