### PR TITLE
Add logging to debug why severity is not set in google_issue_tracker

### PR DESCRIPTION
**Pull request by rmistry**

### CODE REVIEW

**Comment by rmistry** [comment]
PTAL @jonathanmetzman @oliverchang 
CC @micahbales 

(we will remove all of this logging once everything works as expected e2e)

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by rmistry** [comment]
Looks like all checks passed. @jonathanmetzman please merge and deploy at your convenience. TIA!

**Pull request merged**
