### PR TITLE
Bump up libFuzzer/honggfuzz rss limit to 2.5GB.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
@inferno-chromium do we also need to change this part? https://github.com/google/clusterfuzz/blob/master/src/python/platforms/android/adb.py#L37

**Comment by inferno-chromium** [comment]
> @inferno-chromium do we also need to change this part? https://github.com/google/clusterfuzz/blob/master/src/python/platforms/android/adb.py#L37

That is only for cuttlefish bots where we are not running libFuzzing fuzzing, so not impacted. Someday will need to fix that, but unsure if those bots work with higher limit.

**Comment by oliverchang** [comment]
> Will this affect OOMs that are currently open?

Nope, existing testcases have the oom limit as part of the minimized args.

**Pull request merged**
