### PR TITLE
change from testcase_id to existing_testcase_id

### PR DESCRIPTION
**Pull request by lipeng28**
Based on @inferno-chromium's confirmation, submit this PR

### CODE REVIEW

**Comment by lipeng28** [comment]
I signed it! and we'll verify it.

**Comment by oliverchang** [comment]
Can you please fix the formatting/lint error here: https://github.com/google/clusterfuzz/pull/2355/checks?check_run_id=2734259944#step:5:1593 ?

**Comment by lipeng28** [comment]
> Can you please fix the formatting/lint error here: https://github.com/google/clusterfuzz/pull/2355/checks?check_run_id=2734259944#step:5:1593 ?
Hi, I have no idea why this kind of formatting error occurs:
    elif (not existing_testcase.bug_information and
|          not testcase.one_time_crasher_flag):
|      metadata = data_types.TestcaseUploadMetadata.query(
| -        data_types.TestcaseUploadMetadata.testcase_id == existing_testcase_id).get()
| +        data_types.TestcaseUploadMetadata.testcase_id ==
| +        existing_testcase_id).get()
|      if metadata:
|        metadata.status = 'Duplicate'
|        metadata.duplicate_of = testcase_id
| Return code is non-zero (1).
Linting failed, see errors above.
Error: Process completed with exit code 1.

Can you please advise?

**Comment by oliverchang** [comment]
I fixed the formatting issue. Could you please fix the CLA issue in https://github.com/google/clusterfuzz/pull/2355#issuecomment-870315259 ?

**Comment by lipeng28** [comment]
@googlebot I fixed it.

**Pull request closed without merging**
