### PR TITLE
Bump up fork mode frequency to 50% of runs

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fork mode seems to be stable and provide benefits, bump up frequency to 50%.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
cc @kcc

**Comment by jonathanmetzman** [comment]
The main problem with bumping up frequency is it will cause timeouts and OOMs to be reported even less frequency since we aren't reporting those or even surfacing their count in fork mode.

**Comment by jonathanmetzman** [comment]
I think Marty had something.
Since I've enabled this, libFuzzer has found an average of 37 ASAN security bugs per month (including this month which isn't finished) which is up from an average of 31 while AFL has found 16, which is down from an average of 24.

I don't really know if this change is the cause or the number of testcases added is the cause.

**Comment by jonathanmetzman** [comment]
@mbarbella-chromium do you have data on this?

**Comment by jonathanmetzman** [comment]
> LGTM! Do you have any spreadsheet / chart showing performance difference for the fork strategy?

I did some basic queries in internal and found that fork runs are 16% more likely to report a crash (unique and not) than a non fork run. (crashes don't include corpus, startup, timeout or OOM)

**Comment by Dor1s** [comment]
Nice, thanks for sharing!

**Pull request merged**
