### PR TITLE
[fuchsia] Remove old, pre-undercoat code

### PR DESCRIPTION
**Pull request by eepeep**
Now that undercoat is the sole interface between ClusterFuzz and
Fuchsia, support for pre-undercoat builds can be removed. This will
potentially cause failures during regression testing against older
builds, but this should be uncommon and not block any other tasks.

### CODE REVIEW

**Comment by eepeep** [comment]
cc @oliverchang

We don't need to land this immediately, but just wanted to get something up for now.  Do let me know if you see anything I'm missing.

**Review by oliverchang — APPROVED** [review]
nice!

**Comment by oliverchang** [comment]
Could you please investigate the test failure? The error message is not very helpful, but I'm guessing that it's a side effect of some test module not being able to be imported properly.

**Comment by eepeep** [comment]
Sorry, classic mistake of an uncommitted local change... looks good now.

**Comment by oliverchang** [comment]
Thanks!

**Pull request merged**
