### PR TITLE
Use fuzz target name instead of "NULL"

### PR DESCRIPTION
**Pull request by backes**
If no process name is available but we have a fuzz target name, use that
instead of "NULL".
This hopefully reduces the amount of "Abrt · NULL" reports we are
seeing.

### CODE REVIEW

**Comment by backes** [comment]
@oliverchang @jonathanmetzman PTAL
Note that this is based on #3563; the difference is in this commit: https://github.com/google/clusterfuzz/commit/88fd71b15b04d5b753a826f5b9f8ad024903fbc8

See https://groups.google.com/a/google.com/g/clusterfuzz-dev/c/Nq6xWPpGl-c/m/ruP1IVp5AAAJ for context.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by oliverchang** [comment]
This LGTM, other than my comment here in the other PR: https://github.com/google/clusterfuzz/pull/3563#issuecomment-1861821694

**Comment by backes** [comment]
I rebased this now to not depend on #3563. The only difference is that the expected state now has a trailing newline.

Feel free to merge if this looks good.

**Review by oliverchang — APPROVED** [review]

**Comment by backes** [comment]
Are there failing tests? Seems like I don't have access to the results.

**Comment by oliverchang** [comment]
> Are there failing tests? Seems like I don't have access to the results.

Looks like flake. Trying again.

**Comment by backes** [comment]
Thanks a lot! Looking forward to more helpful CF reports, and the respective fixes :D

**Pull request merged**
