### PR TITLE
Revert "Upgrade TensorFlow from 2.3.0 to 2.3.1."

### PR DESCRIPTION
**Pull request by inferno-chromium**
Reverts google/clusterfuzz#2057

This breaks pipenv due to importlib-metadata requirement, and hence CI and bots using it. 

```
Using /usr/local/bin/python3.7m (3.7.7) to create virtualenv…

  creator CPython3Posix(dest=/workspace/.venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/builder/home/.local/share/virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 693, in sync
    pypi_mirror=state.pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2877, in do_sync
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 580, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 512, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 999, in do_create_virtualenv
    project._environment.add_dist("pipenv")
  File "/usr/local/lib/python3.7/site-packages/pipenv/environment.py", line 135, in add_dist
    self.extend_dists(dist)
  File "/usr/local/lib/python3.7/site-packages/pipenv/environment.py", line 127, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "/usr/local/lib/python3.7/site-packages/pipenv/environment.py", line 122, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "/usr/local/lib/python3.7/site-packages/pipenv/environment.py", line 121, in resolve_dist
    dist = working_set.find(req)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 643, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 2.0.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))
```

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Merging to unblock CI.

**Comment by inferno-chromium** [comment]
I think this should fail locally too, if you remove your current pipenv and create a new one.

**Comment by Dor1s** [comment]
> I think this should fail locally too, if you remove your current pipenv and create a new one.

Testing now. It seemed fine locally, although I didn't delete pipenv, only updated it. CI also didn't fail in https://github.com/google/clusterfuzz/pull/2057

**Comment by Dor1s** [comment]
```
...
Bootstrap successfully finished.
+ set +x


Installation succeeded!
Please load environment by running python3.7 -m pipenv shell.

mmoroz@mmoroz3:~/Downloads/clusterfuzz$ git log -n 1
commit 0a453ead25e12c63192f020d97f1be8e5cb4fb12 (HEAD)
Author: Max Moroz <mmoroz@chromium.org>
Date:   Wed Sep 30 17:16:56 2020 -0700

    Upgrade TensorFlow from 2.3.0 to 2.3.1. (#2057)
```

looks good with a new pipenv in a clean checkout

**Comment by inferno-chromium** [comment]
> > I think this should fail locally too, if you remove your current pipenv and create a new one.
> 
> Testing now. It seemed fine locally, although I didn't delete pipenv, only updated it. CI also didn't fail in #2057

CI fails after image is build/updated with build_on_container_builder.sh.

failure was consistent on both github actions and cloud build on my new cl - https://pantheon.corp.google.com/cloud-build/builds/ceca5209-3b3c-4b95-811e-36d511dee087;step=1?organizationId=433637338589&src=ac&project=clusterfuzz-testing-public

i think our default python is 3.8, did you run with python3.7 ? can check more tmrw.

**Pull request merged**
