### PR TITLE
Remove MLRNN

### PR DESCRIPTION
**Pull request by jonathanmetzman**
It's no longer used.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
This might take some more work since some tests may be obsolete now.

**Review by oliverchang — APPROVED** [review]
nice! can we also delete the ml-with-gpu docker images in this repo as well?

**Comment by oliverchang** [comment]
@jonathanmetzman do you wanna clean this up so we can get this merged? It would be nice to clean things up here :)

**Comment by jonathanmetzman** [comment]
I've cleaned it up. Want to look again?

**Review by oliverchang — APPROVED** [review]
nice! LGTM

**Pull request merged**
