### PR TITLE
Install Java 17 on images

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
THis doesn't work. We need java_15

**Comment by vitorguidi** [comment]
> THis doesn't work. We need java_15

Why? What broke?

**Comment by jonathanmetzman** [comment]
> > THis doesn't work. We need java_15
> 
> Why? What broke?

JNI

**Comment by jonathanmetzman** [comment]
Confirmed this works with both versions of Java.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
