### PR TITLE
Fix failing unittests

### LINKED ISSUE #2246: Tests fail on fresh installs
Some unittests fail on my machine and on @vanhauser-thc 's machine on HEAD:
```
======================================================================
ERROR: test_corpus_subset (tests.core.bot.fuzzers.afl.afl_launcher_test.AflFuzzInputDirectoryTest)
Tests that create_new_if_needed works as intended when told to use a 75
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: '/inputdir/in1' -> '/tmp/afl_input_dir/in1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 271, in test_corpus_subset
    afl_input = self._new_afl_input()
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 203, in _new_afl_input
    return launcher.AflFuzzInputDirectory(self.INPUT_DIR, self.TARGET_PATH,
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 414, in __init__
    self.create_new_if_needed()
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 482, in create_new_if_needed
    shutil.copy(src_path, dst_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

======================================================================
ERROR: test_create_new_if_needed (tests.core.bot.fuzzers.afl.afl_launcher_test.AflFuzzInputDirectoryTest)
Test that the AflFuzzInputDirectory.create_new_if_needed() method works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: '/inputdir/in1' -> '/tmp/afl_input_dir/in1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 229, in test_create_new_if_needed
    afl_input = self._new_afl_input()
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 203, in _new_afl_input
    return launcher.AflFuzzInputDirectory(self.INPUT_DIR, self.TARGET_PATH,
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 414, in __init__
    self.create_new_if_needed()
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 482, in create_new_if_needed
    shutil.copy(src_path, dst_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

======================================================================
ERROR: test_create_new_if_needed_subdirs (tests.core.bot.fuzzers.afl.afl_launcher_test.AflFuzzInputDirectoryTest)
Test AflFuzzInputDirectory.create_new_if_needed on an input directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: '/inputdir/in1' -> '/tmp/afl_input_dir/in1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 242, in test_create_new_if_needed_subdirs
    afl_input = self._new_afl_input()
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 203, in _new_afl_input
    return launcher.AflFuzzInputDirectory(self.INPUT_DIR, self.TARGET_PATH,
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 414, in __init__
    self.create_new_if_needed()
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 482, in create_new_if_needed
    shutil.copy(src_path, dst_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

======================================================================
ERROR: test_copy_crashes_if_needed (tests.core.bot.fuzzers.afl.afl_launcher_test.AflFuzzOutputDirectoryTest)
Test that copy_crashes_if_needed works as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: '/tmp/afl_output_dir/default/crashes/id:000012,src:000000,op:flip1,pos:1,+cov' -> '/testcase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 394, in test_copy_crashes_if_needed
    self.afl_output.copy_crash_if_needed(testcase_path)
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 220, in copy_crash_if_needed
    shutil.copyfile(crash_path, testcase_path)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

======================================================================
ERROR: test_run_afl_fuzz_crashing_input (tests.core.bot.fuzzers.afl.afl_launcher_test.AflRunnerTest)
Test AflRunner.run_afl_fuzz_and_handle_error works as intended when there
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: '/inputdir/badfile' -> '/testcase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/clusterfuzz/src/python/tests/core/bot/fuzzers/afl/afl_launcher_test.py", line 785, in test_run_afl_fuzz_crashing_input
    self.runner.run_afl_fuzz(self.args).return_code,
  File "/home/user/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py", line 889, in run_afl_fuzz
    shutil.copyfile(crash_path, self.testcase_file_path)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

----------------------------------------------------------------------
Ran 50 tests in 2.246s

FAILED (errors=5)

======================================================================
ERROR: test_app (tests.core.local.butler.deploy_test.DeployTest)
Test deploy app.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: './configs/test/gae/prod3/app.yaml' -> 'src/appengine/app.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/clusterfuzz-IJC_JKc5/lib/python3.8/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/user/clusterfuzz/src/python/tests/core/local/butler/deploy_test.py", line 148, in test_app
    deploy._prod_deployment_helper('/config_dir',
  File "src/local/butler/deploy.py", line 412, in _prod_deployment_helper
    _deploy_app_prod(
  File "src/local/butler/deploy.py", line 98, in _deploy_app_prod
    rebased_yaml_paths = appengine.copy_yamls_and_preprocess(
  File "src/local/butler/appengine.py", line 63, in copy_yamls_and_preprocess
    shutil.copy(path, rebased_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

Stdout:
Deploying test-clusterfuzz to prod.

======================================================================
ERROR: test_app_retry (tests.core.local.butler.deploy_test.DeployTest)
Test deploy app with retries.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: './configs/test/gae/prod3/app.yaml' -> 'src/appengine/app.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/clusterfuzz-IJC_JKc5/lib/python3.8/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/user/clusterfuzz/src/python/tests/core/local/butler/deploy_test.py", line 222, in test_app_retry
    deploy._prod_deployment_helper('/config_dir',
  File "src/local/butler/deploy.py", line 412, in _prod_deployment_helper
    _deploy_app_prod(
  File "src/local/butler/deploy.py", line 98, in _deploy_app_prod
    rebased_yaml_paths = appengine.copy_yamls_and_preprocess(
  File "src/local/butler/appengine.py", line 63, in copy_yamls_and_preprocess
    shutil.copy(path, rebased_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

Stdout:
Deploying test-clusterfuzz to prod.

======================================================================
ERROR: test_app_retry_failure (tests.core.local.butler.deploy_test.DeployTest)
Test deploy app with retries (failure).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: './configs/test/gae/prod3/app.yaml' -> 'src/appengine/app.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/clusterfuzz-IJC_JKc5/lib/python3.8/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/user/clusterfuzz/src/python/tests/core/local/butler/deploy_test.py", line 287, in test_app_retry_failure
    deploy._prod_deployment_helper('/config_dir',
  File "src/local/butler/deploy.py", line 412, in _prod_deployment_helper
    _deploy_app_prod(
  File "src/local/butler/deploy.py", line 98, in _deploy_app_prod
    rebased_yaml_paths = appengine.copy_yamls_and_preprocess(
  File "src/local/butler/appengine.py", line 63, in copy_yamls_and_preprocess
    shutil.copy(path, rebased_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 29] Illegal seek

Stdout:
Deploying test-clusterfuzz to prod.

======================================================================
ERROR: test_app_staging (tests.core.local.butler.deploy_test.DeployTest)
Test deploy app to staging.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 152, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 29] Illegal seek: './configs/test/gae/staging3/staging.yaml' -> 'src/appengine/staging.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/clusterfuzz-IJC_JKc5/lib/python3.8/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/user/clusterfuzz/src/python/tests/core/local/butler/deploy_test.py", line 202, in test_app_staging
    deploy._staging_deployment_helper()
  File "src/local/butler/deploy.py", line 380, in _staging_deployment_helper
    _deploy_app_staging(project, yaml_paths)
  File "src/local/butler/deploy.py", line 121, in _deploy_app_staging
    rebased_yaml_paths = appengine.copy_yamls_and_preprocess(
  File "src/local/butler/appengine.py", line 63, in copy_yamls_and_preprocess
    shutil.copy(path, rebased_path)
  File "/usr/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 275, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    if offset == 0 and os.lseek(outfd, 0, os.SEEK_CUR) == 0:
OSError: [Errno 9] Bad file descriptor

Stdout:
Deploying test-clusterfuzz to staging.

----------------------------------------------------------------------
Ran 13 tests in 0.399s

FAILED (errors=4)

Ran 1465 tests (176 skipped, 9 errors, 0 failures).
```

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fix unittests failing on HEAD because of a bug in pyfakefs.
Since all of these tests used fakefs, I tried upgrading it, which seemed to work.
Also upgraded the pipenv.lock file.
Fixes #2246

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Unittest failure is spurious.

**Pull request merged**
