### PR TITLE
Stack analyzer: Ignore googletest-specific stack frames

### PR DESCRIPTION
**Pull request by mi-ac**
This will allow using gtest asserts in test cases, which is useful for fuzztest cases. Without ignoring gtest frames, the stack analyzer will dedupe too many different assertion failures. An example is: https://clusterfuzz.com/testcase-detail/5122010454097920

The associated Chromium bug is: https://crbug.com/1494445

### CODE REVIEW

**Review by adetaylor — APPROVED** [review]

**Comment by oliverchang** [comment]
Thanks! Would you mind adding a test for this?

**Comment by mi-ac** [comment]
> Thanks! Would you mind adding a test for this?

Sure.  Are there instructions somewhere how to run the tests locally?

**Comment by mi-ac** [comment]
> > Thanks! Would you mind adding a test for this?
> 
> Sure. Are there instructions somewhere how to run the tests locally?

Managed. Added a test based on the current running example. We might maybe also want to ignore more of centipede, but I don't think it's really in the way right now...

**Comment by oliverchang** [comment]
> > > Thanks! Would you mind adding a test for this?
> > 
> > 
> > Sure. Are there instructions somewhere how to run the tests locally?
> 
> Managed. Added a test based on the current running example. We might maybe also want to ignore more of centipede, but I don't think it's really in the way right now...

thanks!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
