### PR TITLE
Fix some unicode decode issues with newstr and exceptions.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
TBR. /gcbrun

**Comment by oliverchang** [comment]
Created https://github.com/google/clusterfuzz/issues/1420 for that.

**Comment by inferno-chromium** [comment]
Do these cover all the str(e) we append in errors ?

**Comment by oliverchang** [comment]
> Do these cover all the str(e) we append in errors ?

These should be the majority, since they're coming from process output where this is more likely.

**Pull request merged**
