### PR TITLE
Remove performance analyzer

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @marktefftech

**Review by marktefftech — APPROVED** [review]
LGTM

**Review by oliverchang — APPROVED** [review]

**Comment by leonasdev** [comment]
@jonathanmetzman @oliverchang 
Hi, would you mind to let us know why this feature is removed?
Doesn't performance report can help user to know what blocks in fuzzing?

**Comment by jonathanmetzman** [comment]
1. It was flawed and in my experience wasn't very informative.
2. Some internal users were complaining about it confusing their users.

Did you guys use it?

**Comment by leonasdev** [comment]
> 1. It was flawed and in my experience wasn't very informative.
> 2. Some internal users were complaining about it confusing their users.
> 
> Did you guys use it?

Not really use it frequently.

But I was curious if the weight of fuzzer and job is calculated similars to performance report, does that means the weight is also flawed?

@jonathanmetzman

**Pull request merged**
