### PR TITLE
Register the new google_issue_tracker

### PR DESCRIPTION
**Pull request by rmistry**

### CODE REVIEW

**Comment by rmistry** [comment]
@oliverchang PTAL

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
Please resolve the conflicts. Otherwise this looks good!

**Comment by rmistry** [comment]
> Please resolve the conflicts. Otherwise this looks good!

Done. PTAL.

**Comment by rmistry** [comment]
Thanks for the merge!

**Pull request merged**
