### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
TBR

**Review by oliverchang — COMMENTED** [review]
LGTM, but any reason in particular for the major version bump?

**Comment by inferno-chromium** [comment]
> LGTM, but any reason in particular for the major version bump?

that was a mistake, fixed and removed that tag, rereleased as 2.3.0

**Comment by oliverchang** [comment]
Thanks!

**Pull request merged**
