### PR TITLE
Revert "libFuzzer: use two step merge after fuzzing for accurate stats (#802)."

### PR DESCRIPTION
**Pull request by Dor1s**
Reverts google/clusterfuzz#815

Both internal and external instances seem to be reporting errors with some fuzz targets. Might be that those are using old libFuzzer, but might be a bug in the code I wrote. Reverting for now.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I was curious if something happened since AFL and LF are performing nearly the same this month (https://docs.google.com/spreadsheets/d/18q5JGzU2pGv4FJhRjeVkXGi3bZ2dRU7SxagC_aupzAo/edit#gid=1198170776) unlike nearly every other month.

**Comment by Dor1s** [comment]
CI is happy, landing and deploying.

**Comment by Dor1s** [comment]
@jonathanmetzman that is very suspicious indeed!

**Pull request merged**
