### PR TITLE
Fix issue with error handling

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @flowerhack

**Comment by jonathanmetzman** [comment]
Completely absurd that pylint doesn't catch this. I think it's because this type of analysis gets broken by the way we use pylint (not on the entire project at once).

**Comment by flowerhack** [comment]
@jonathanmetzman (Out of curiosity, why don't we run pylint on the entire project at once? Would be happy to look into changing that unless it's doomed)

**Comment by jonathanmetzman** [comment]
I'm changing things to do that as we speak. I don't know the answer but I think it's bad that we don't do this, and agree we should be running it on the entire project.
no-member has a lot of false positives but better to manually disable them one by one.

**Review by Alan32Liu — COMMENTED** [review]
LGTM

**Pull request merged**
