### PR TITLE
Use explicit instance dir for afl-fuzz, needed for afl++

### PR DESCRIPTION
**Pull request by inferno-chromium**
afl++ defaults to -S default now. So, explicitly provide one.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
> afl++ defaults to -S default now. So, explicitly provide one.

Is there some kind of error this fixes?
I think we need to swap out the afl-fuzz binaries for afl++ ones for this to pass tests.

**Comment by inferno-chromium** [comment]
TBR to unblock bots, and see if we need to revert oss-fuzz commit/it sticks.

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Isn't this going to break internal ClusterFuzz?

**Comment by inferno-chromium** [comment]
> Isn't this going to break internal ClusterFuzz?

-S is supported by regular afl.

**Comment by jonathanmetzman** [comment]
> > Isn't this going to break internal ClusterFuzz?
> 
> -S is supported by regular afl.

Nice!

**Pull request merged**
