### PR TITLE
[AFL] Recover from forkserver timeouts by warming up filesystem cache before fuzzing

### LINKED ISSUE #1112: AFL timing out before forkserver initialization in Chrome targets
This is a frequent source of AFL errors see [here](https://console.cloud.google.com/logs/viewer?resource=gce_instance%2Finstance_id%2F100060469473385782&logName=projects%2Fgoogle.com:clusterfuzz%2Flogs%2Fbot&expandAll=false&timestamp=2019-10-17T19:17:47.450000000Z&project=google.com:clusterfuzz&organizationId=433637338589&src=ac&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=error_group(%22COfK4sao5tSJ1QE%22)&interval=PT1H&scrollTimestamp=2019-10-17T14:16:16.729219573Z&dateRangeStart=2019-10-17T18:17:47.449Z&dateRangeEnd=2019-10-17T19:17:47.449Z) for example. 

This only started happening when we switched to dynamic linking.

Locally (and on the ClusterFuzz bots) I found that this error can be prevented by warming up the filesystem cache by executing the binary once before running it in AFL. After doing this, the target won't have problem until one executes this command to drop the cache: `echo 3 > /proc/sys/vm/drop_caches`.

Any solution that involves warming up the cache is probably fragile since I assume the parts of the cache can be evicted at any time.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fixes #1112

### CODE REVIEW

**Comment by oliverchang** [comment]
Is this still relevant? Can we close this?

**Comment by jonathanmetzman** [comment]
Closing.

**Pull request closed without merging**
