### PR TITLE
Jira integration fixes

### PR DESCRIPTION
**Pull request by quanyangsc**
This fixes two Jira integration issues:
1. Jira objects are not JSON encodable, so this fixes it by returning the raw representation of the Jira object which happens to be in JSON.
2. The format string in the find_issues method wasn't assigned back to the variable and so it wasn't working as intended.

Apart from that, this also implements the `find_issues_url` method by reusing the code from `find_issues`.

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]
LGTM, thanks!

**Comment by quanyangsc** [comment]
The latest lint error doesn't seem to be relevant to my changes, I could rename the variable back to `o` as the linter is asking.
@inferno-chromium @oliverchang wdyt?

**Comment by oliverchang** [comment]
> The latest lint error doesn't seem to be relevant to my changes, I could rename the variable back to `o` as the linter is asking. @inferno-chromium @oliverchang wdyt?

Sorry about that. I just edited this in your PR to fix that issue.

**Pull request merged**
