### PR TITLE
Create .lgtm.yml to run tests on Python 2.7

### LINKED ISSUE #190: Add .lgtm.yml
@evverx thank you for adding ClusterFuzz to LGTM.com.
I created a new issue because I don't want to clutter #126.
On further thought, it seems like adding a .lgtm.yml may be a good idea (even if it means I have to conceed static analysis can be useful :-)

I'm just curious what's the advantage of adding the file if #126 fixes most of the python3-python2 issues LGTM.com is currently running into?

Feel free to add the file in a PR if you'd like. Or I can do this since I (incorrectly) preemptively rejected the PR last time :)
CC @cclauss

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #190

### CODE REVIEW

**Comment by evverx** [comment]
I think checks like these should be as close to the code as possible. I mean, if anyone here cares about issues that can be found with `flake8`, then it should be run by the CI when PRs are opened (and probably something like `buttler flake8` should be added too or maybe `buttler lint` should be extended a little bit). LGTM is currently too far and, hence, it doesn't seem to be very useful. So `-1` from me.

**Comment by cclauss** [comment]
Look below... There are currently two CI jobs being run: __cla/google__ is run automatically as soon as a PR is submitted.  __Trigger:__ will only be run when at least one maintainer has approved the changes.  That approval may take hours or days in which .  LGTM (if enabled for this repo) would give the committee ___immediate___ feedback it their PR contained a syntax error, undefined name, etc.  Also the output of LGTM is visible to everyone while the output of __Trigger:__ is only visible to insiders (open source, closed test results) so the output must be manually sent to the committee as seen at 
* https://github.com/google/clusterfuzz/pull/126#issuecomment-461994529 and again at 
* https://github.com/google/clusterfuzz/pull/126#issuecomment-463003325

**Comment by evverx** [comment]
@cclauss I kind of started to discuss that issue in https://github.com/google/clusterfuzz/pull/138#issuecomment-461878606 and am waiting for feedback. If you think that it would be great to be able to see why the CI fails, it would probably better to join the discussion there to help to fix the underlying issue instead of trying to get it around with LGTM. Apart from that, I think that chaining "analysis" tools that potentially prevents LGTM itself from analyzing the code isn't exactly the right approach (I'd add that, in a way, it's abuse of the LGTM infrastructure).

**Comment by cclauss** [comment]
Look below... There are currently two CI jobs being run: __cla/google__ is run automatically as soon as a PR is submitted.  __Trigger:__ will only be run when at least one maintainer has approved the changes.  That approval may take hours or days in which .  LGTM (if enabled for this repo) would give the committee ___immediate___ feedback it their PR contained a syntax error, undefined name, etc.  Also the output of LGTM is visible to everyone while the output of __Trigger:__ is only visible to insiders (open source, closed test results) so the output must be manually sent to the committee as seen at 
https://github.com/google/clusterfuzz/pull/126#issuecomment-461994529 and again at

**Comment by evverx** [comment]
@cclauss I'm not sure what the last comment is about. Have you read my comments? Is something that I wrote about public feedback from the CI or abusing the LGTM infrastructure or extending "butler lint" not clear enough? (I'm not a native speaker of English so it happens sometimes)

**Comment by jonathanmetzman** [comment]
>@cclauss I kind of started to discuss that issue in [#138 (comment)](https://github.com/google/clusterfuzz/pull/138#issuecomment-461878606) and am waiting for feedback.

I think we are planning on switching to travis CI or something similar which at the very least will have public results (not sure about letting people trigger builds).

**Pull request closed without merging**
