### PR TITLE
Add support for newer nullptr pointer-overflow checks.

### PR DESCRIPTION
**Pull request by mbarbella-chromium**
This will also start logging an error if we hit our catch all case for UBSan so we know that new signatures need to be added.

### CODE REVIEW

**Comment by mbarbella-chromium** [comment]
PTAL

**Comment by mbarbella-chromium** [comment]
This should fix issue #1220

**Comment by Dor1s** [comment]
Nice, the logging appears to be already working!

```
Unknown UBSan crash type: null pointer passed as argument 1, which is declared to never be null
```

**Pull request merged**
