### PR TITLE
[jazzer] Handle binaries properly

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Make sure we always unpack jazzer binaries and that we don't treat
them as fuzz targets.
Related: https://github.com/google/oss-fuzz/issues/5178

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @fmeum

**Review by inferno-chromium — APPROVED** [review]
Thanks!

**Comment by jonathanmetzman** [comment]
Build failure looks spurious to me.

**Review by oliverchang — COMMENTED** [review]
LGTM

**Pull request merged**
