### PR TITLE
Set minimum logging level for AppEngine to INFO.

### PR DESCRIPTION
**Pull request by inferno-chromium**
This avoid the noise from datastore api debug logs.

### CODE REVIEW

**Comment by mbarbella-chromium** [comment]
Is this specific to the API on app engine? Do we also see similar logging on the bots?

**Comment by inferno-chromium** [comment]
> Is this specific to the API on app engine? Do we also see similar logging on the bots?

For bots, we already do INFO. See few lines down.
  logger.setLevel(logging.INFO)

**Pull request merged**
