### PR TITLE
Fix a unicode exception in libFuzzer/engine.py.

### PR DESCRIPTION
**Pull request by mbarbella-chromium**

### CODE REVIEW

**Comment by oliverchang** [comment]
> There are many more places with this pattern where we add result.output, see many places in this file, i guess in afl, honggfuzz too and also corpus pruning task. @oliverchang - thoughts ? should we use repr ?

The more general fix here would be to use UnicodeProcessRunner for all the LibFuzzerRunner classes, which is already done for honggfuzz and AFL.

**Comment by inferno-chromium** [comment]
> This change LGTM itself, but agreed there's a more general fix needed.

Lets do this UnicodeProcessRunner fix, i dont like this fix please, it is incomplete i feel like. @oliverchang - is it easy to change the remaining places, can you do this ?

**Comment by oliverchang** [comment]
This should be fixed more generally by https://github.com/google/clusterfuzz/pull/1595

**Pull request closed without merging**
