### PR TITLE
Add newlines to corpus pruning exception messages.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@Dor1s fyi, you should stop seeing those emails with long output after this.

**Comment by Dor1s** [comment]
> @Dor1s fyi, you should stop seeing those emails with long output after this.

ack, will keep an eye

**Comment by Dor1s** [comment]
Looks like a line break doesn't stop all the message from going into the error: https://pantheon.corp.google.com/errors/CIn9yNWGqJaRNg?time=P1D&project=google.com:clusterfuzz

**Comment by Dor1s** [comment]
should we do something like this:

```
logs.log_error('Merging new testcases timed out', output=result.output)
raise engine.TimeoutError('Merging new testcases timed out.')
```

would StackDriver associate the log message and the exception?

**Pull request merged**
