### PR TITLE
[consolidation] Add module for executing untrusted tasks (utasks)

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @flowerhack

**Comment by jonathanmetzman** [comment]
Related: https://github.com/google/clusterfuzz/issues/3008

**Review by jonathanmetzman — COMMENTED** [review]
TBR

**Review by Alan32Liu — COMMENTED** [review]
LGTM.

**Pull request merged**
