### PR TITLE
Ignore pyenv configuration file.

### PR DESCRIPTION
**Pull request by letitz**
This allows using [pyenv](https://github.com/pyenv/pyenv) to manage python versions.

### CODE REVIEW

**Comment by letitz** [comment]
@jonathanmetzman for review.

**Comment by jonathanmetzman** [comment]
> This allows using [pyenv](https://github.com/pyenv/pyenv) to manage python versions.

Sorry could you explain how and why we want this? I don't know these.

**Comment by letitz** [comment]
Sure! pyenv is a nice tool for installing multiple python versions from source and manage them automatically. One can set the default python version for a project using e.g. `pyenv local 3.7`, which basically does `echo 3.7 > .python-version`.

**Comment by jonathanmetzman** [comment]
Didn't know about this functionality. I didn't know pyenv did anything except making updating dependencies painful.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by letitz** [comment]
Note that `pyenv != pipenv`, `pyenv` is about installing different python versions, whereas `pipenv` is about installing python package dependencies.

**Pull request merged**
