### PR TITLE
Update pipenv to latest version 2023.12.1

### PR DESCRIPTION
**Pull request by letitz**
This would allow use of package categories, which might help simplify dependency management.

Curious to see whether this breaks things or not, most notably CI.

### CODE REVIEW

**Comment by letitz** [comment]
I want to test it out locally to see if it works on my machine (tm), then I guess we can try merging!

**Comment by letitz** [comment]
I can confirm that `local/install_deps.bash` works with the updated pipenv. I'll see about updating the version used on Mac too.

**Comment by letitz** [comment]
On Mac `local/Brewfile` is used to install pipenv using homebrew, with no version specification.

I think this is good to merge!

**Comment by letitz** [comment]
Friendly ping!

**Review by jonathanmetzman — APPROVED** [review]

**Pull request merged**
