### PR TITLE
Display hotlist IDs for the wrong component/CLs labels

### PR DESCRIPTION
**Pull request by rmistry**

### CODE REVIEW

**Comment by rmistry** [comment]
PTAL @jonathanmetzman

**Comment by jonathanmetzman** [comment]
Hey All-tests seems to be running without gcbrun for you.

**Comment by rmistry** [comment]
> Hey All-tests seems to be running without gcbrun for you.

Huh, that's interesting. I don't think I ever saw the invitation for collaborators, but maybe it worked automatically?

**Comment by rmistry** [comment]
Looks like all tests passed. Please merge when you get a chance.

**Pull request merged**
